### ISSUE TITLE
Receive MQTT Commands

### ISSUE THREAD

**Issue by Schnittcher** [omersiar/esp-rfid#102]
It would be nice if you could execute commands via MQTT to switch the relay. Is that planned?

**Comment by omersiar** [comment]
Can you share how can it be used?

**Comment by Schnittcher** [comment]
Yes, i want to integrate it in our Smart Home, and I want to implement the user accesses there.

**Comment by quikote** [comment]
+1
I would like to operate de door from Home Assistant using MQTT, so I need to send a MQTT message from my home controller to activate the lock as a allowed RFID card was readed

**Comment by omersiar** [comment]
You can always send WebSocket messages.

**Comment by Schnittcher** [comment]
This is okay. I will test it. Thanks.
Can you give me an example?

**Comment by Schnittcher** [comment]
I found the testrelay command and userlist command, so I can control the relay and list all users. Can you still tell me how I can add users?

**Comment by omersiar** [comment]
`"command": "userfile"` is the for adding new user.

**Comment by omersiar** [comment]
Did you managed to send WebSocket commands via Home Assistant?

**Comment by quikote** [comment]
I don't know how to.... :-(((

**Comment by omersiar** [comment]
Currently we have WebUI to setup everything. MQTT was never an intended feature to support, It will take longer to support incoming mqtt commands. Closing this for now.

**Comment by zuhra031** [comment]
@omersiar 
Can you provide WebSocket commands?

I would like to trigger relay from OpenHab2 or via local web server or anything else as long as I don't need to login every time into esp to open door remotely (click on relay test btn).

Edit: idea for improvement: trigger relay test and add to log when received specific mqtt msg on specific topic, eq. "frontdoor/eps-rfid/relay/" and msg "testRelay"
