### ISSUE TITLE
Nothing works... PN532

### ISSUE THREAD

**Issue by JuculianD** [omersiar/esp-rfid#105]
After I tried it with 2 Wiegand Reader, 5 wemos d1 mini, I came to the conclusion that only the MFRC reader worked. I now want to use the PN532 but unfortunately, I got many problems.
The wemos d1 mini does not want to start with the PN532 connected and often, it needs several attempts to flash the Wemos D1 Mini with the included script.

Can someone please help? It is urgent.

**Comment by omersiar** [comment]
PN532 support is experimental, but i did not exclude it from master code base.  Problem with the PN532 is there are no non-blocking libraries for it.  Included library is actually non-blocking but it is not tested widely, original author of the library initially made it for the Teensy boards.  

At the end of the day, I recommend using MFRC522 for RFID hardware, also Wiegand reader support is coming from the community and currently i can not test them means stability may vary.

You can reduce flashing speed for better stability when flashing, 115200 baud rate is the most stable one i believe.

**Comment by JuculianD** [comment]
Thank you very much! I will use the MFRC522 for now. Do you think that I can increase the reading range a bit, like up to 6-7cm?

**Comment by omersiar** [comment]
Did you try max gain setting on mfrc522?

**Comment by JuculianD** [comment]
yes

**Comment by omersiar** [comment]
@JuculianD You will need better antenna design to for better range.
