### ISSUE TITLE
Access Type Selection

### ISSUE THREAD

**Issue by araziforum** [omersiar/esp-rfid#107]
![1](https://user-images.githubusercontent.com/32632760/38975739-ab4b338c-43b7-11e8-8bed-a869905c3909.JPG)
Hi. In first thx for your project. I want to ask you about "Access Type" menu. I choose "Within Selected Hours" but how can I edit or change this hours settings?

**Comment by omersiar** [comment]
Hello @araziforum,

I taught that i could quickly implement these settings but i am afraid that the most of the access type option currently not implemented.  Sorry for the inconvenience,  i should remove them until it's done.

**Comment by araziforum** [comment]
Thx for your very fast response. I hope you will succeed in your work. Have a nice day.

**Comment by araziforum** [comment]
@omersiar Hocam anladığım kadarıyla Türksünüz. Bunun Türkçe olanından yapmak mümkün müdür?

**Comment by omersiar** [comment]
Merhaba,

Şu an icin dil degistirme secenegi yok, coklu dil destegi sonraki surumlere eklenebilir, o zaman diger dilleri eklemek mumkun olacak.
