### ISSUE TITLE
Cannot edit HTML file 

### ISSUE THREAD

**Issue by dalukac** [omersiar/esp-rfid#110]
Hi. I want to make some small visual changes to web ui but when i edit index.html file and upload it nothing changes ..am i doing something wrong ? thanks for reply

**Comment by omersiar** [comment]
Yes, currently development of web pages is not documented, simply editing index.html does not make any changes on flashed firmware.

**Comment by dalukac** [comment]
so it's there some way to edit it ?

**Comment by omersiar** [comment]
Yes, you will need nodejs and gulp for this, then you will need to run https://github.com/omersiar/esp-rfid/blob/stable/tools/webfilesbuilder/gulpfile.js script to prepare web files then you can compile as usual with platformio.

**Comment by omersiar** [comment]
Sorry for the closing issue without proper reply to your last message, i did not see you asked for it. You can re-open this if you want further help.

**Comment by abanoubmounir465** [comment]
> Yes, you will need nodejs and gulp for this, then you will need to run https://github.com/omersiar/esp-rfid/blob/stable/tools/webfilesbuilder/gulpfile.js script to prepare web files then you can compile as usual with platformio.

hi 
can you explanation with steps please
thank you
