### ISSUE TITLE
MQTT User/Pass not working

### ISSUE THREAD

**Issue by vr6syncro** [omersiar/esp-rfid#111]
If i place Username and Passwort for MQTT it is not working.

I get this Error on my broker:

```
mqtt.0 | 2018-04-28 00:23:52.671 | warn | Client [esp82662c82e4] has invalid password(gular.woff) or username(lflings-regular.woff)
-- | -- | -- | --
```

**Comment by omersiar** [comment]
This is because of a known bug.

Please refer this for a quick workaround.
https://github.com/omersiar/esp-rfid/issues/87#issuecomment-378342351
