### ISSUE TITLE
Led and Buzzer Support

### ISSUE THREAD

**Issue by araziforum** [omersiar/esp-rfid#114]
Hi. Can you add a buzzer controller pin in hardware menu? (Hocam kartın sistemi çalıştırdığını anlamak için buzzer eklenmesi mümkün mü? Bu güzel bir ek özellik olacaktır. Röleyi seçtiğimiz gibi buzzer için de bir pin seçilmesi mümkün olur mu?)

**Comment by omersiar** [comment]
Before adding buzzer or led hardware support, i want to release at least one stable, reliable version of esp-rfid, until then it can be done manually by yourself.  Of course this does not mean i am not open to pull requests, it is always welcomed.

Merhaba,

Buzzer veya led eklenmesi için henüz erken.  Kararlı bir sürüm çıkarana kadar eklemeyi planlamıyorum, daha doğrusu öncelikli değil.

**Comment by omersiar** [comment]
@chaintip

**Comment by chaintip** [comment]
`0.00358035 BCH`| `~   4.97 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4v2fsutwt6c4n932w4j6wy20emkucv2nyqw3) to this issue by @omersiar.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/30), get a pull request merged with ```@chaintip fixes #114``` in the creation comment.

**Comment by araziforum** [comment]
Eventlogs bölümü verileri listelemiyor. acaba sorun sadece bende mi yoksa genel bir durum mu? "Please wait while fetching data..." yazıp kalıyor. yarım saat bekledim sonuç alamadım. clear log a basıyorum durum değişmiyor.

**Comment by omersiar** [comment]
Clear Log butonu calisiyor mu? Chrome f12 gelistirici araclarinda network bolumu var, orada ws sekmesi var veri gelip gidiyor mu?

**Comment by araziforum** [comment]
sadece sayfayı yenile dediğimde şifre soruyor o sırada veri akışı oluyor dediğiniz yerde ancak menüler arasındaki geçişte herhangi bir değişiklik olmuyor network bölümünde. access log bölümüne clear yaptığımda da bişey olmadı. sadece f5 yapınca orada akış oluyor
![12](https://user-images.githubusercontent.com/32632760/40055032-42600e7c-584f-11e8-8cd1-83dc60c037b7.JPG)

Yazılımı atom ile atınca 0.7.5 sürümü göründü ve açılmayan access log kısmı sorunu düzeldi.

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/30), get a pull request merged with ```@chaintip fixes #114``` in the creation comment.

**Comment by araziforum** [comment]
802.1x eap Wifi bağlantısı yapabilmek için Wifi bağlantı ayarlarına kullanıcı adı ve şifre girecek şekilde bir bölüm yapılabilir mi?

**Comment by m00st** [comment]
Here is a very nice implementation using a simple 5v buzzer and one or more ws2812 leds: https://www.youtube.com/watch?v=BvjtoR0eq_M

Similar functionality would be really aweseome.
