### ISSUE TITLE
Time zone doesn't works

### ISSUE THREAD

**Issue by quikote** [omersiar/esp-rfid#116]
It doesn't matter which time zone I select. The device time is always 1 hour behind the real time in my country. The sync brower time to device doesn't fix the problem and neither the NTP server from my country.

**Comment by omersiar** [comment]
@quikote Hello,

Is this can be bacause of DST (Daylight Saving Time)? It is hard to know every countries' DST policy, for example I do not even know my country's current DST policy.

Basically you need to set the time difference between your local time and UTC time.  

For example we were on GMT +2 country list but now, we did not rolled back to DST time so we become a GMT +3 country. (this is pure madness)

Also if this is not the case i need to know your settings.

**Comment by omersiar** [comment]
Is this still an issue?

**Comment by farkasgzoltan** [comment]
https://github.com/RoboUlbricht/arduinoslovakia/tree/master/esp8266/ntp_client

https://github.com/JChristensen/Timezone
or
https://platformio.org/lib/show/1276/simpleDSTadjust

https://codebender.cc/example/Timezone/WorldClock#WorldClock.ino

https://github.com/vancegroup-mirrors/avr-libc/blob/master/avr-libc/include/util/eu_dst.h
https://github.com/vancegroup-mirrors/avr-libc/blob/master/avr-libc/include/util/usa_dst.h

RTC ds3232
http://www.instructables.com/id/Adding-Daylight-Savings-Time-to-Your-RTC/

change ntp to api.timezonedb.com etc....
const char* host      = "http://api.timezonedb.com/v2/get-time-zone?key=******&format=xml&fields=formatted&by=zone&zone=Europe/Berlin";

**Comment by omersiar** [comment]
Standart getTimezoneOffset() function returns invalid offset for Turkey on Chrome, Firefox does not have this issue, so this is a chromium bug. Reported to Chromium Devs.
