### ISSUE TITLE
Wiegand reader

### ISSUE THREAD

**Issue by PascalSI** [omersiar/esp-rfid#119]
Hi, i would like to know if the ESP-Rfid is working with any reader in the Wiegand protocol? With this reader will work: https://www.zkteco.eu/index.php/categories-11/access-control-systems/rfid-external-readers/wiegand-reader

**Comment by teriall** [comment]
Yea, it's working pretty well with Wiegand readers. As well using similar reader with 125KHz/13.56MHz was bought from aliexpress (http://ali.onl/109k)

**Comment by PascalSI** [comment]
Thanks, i already saw, i did not look at the descriptions ... Can i connect only one reader or two?
