### ISSUE TITLE
esp-rfid (wemos) can subscribe (or publish) multiple topics in MQTT?

### ISSUE THREAD

**Issue by nbaglietto** [omersiar/esp-rfid#121]
What are the topics that you publish or can you subscribe?
Does the compiled firware have any topics that allow me to trigger the relay?
I want to make a button in node-network that allows me to activate the relay to which topic I have to subscribe?

I do not speak English so I attach a diagram with what I want to do

Thank you very much !!!
![esp-rfid-door](https://user-images.githubusercontent.com/37049113/41197146-d1e2ab8e-6c29-11e8-99dd-3380193590cc.jpg)

**Comment by omersiar** [comment]
Currently esp-rfid publishes UID and User Name (if available) of scanned RFID tag on given topic which is configured via Web UI.

**Comment by omersiar** [comment]
You need to connect to WebSocket server on esp-rfid to activate the relay, you need to send simple text websocket message "{\"command\":\"testrelay\"}"
