### ISSUE TITLE
current platform triggers restart for wiegand readers

### ISSUE THREAD

**Issue by nardev** [omersiar/esp-rfid#124]
Current plarform set in platformio.ini triggers ESP8266 restart. However, i didn't notice any errors if we use
platform = espressif8266
with
build_flags = -Wl,-Tesp8266.flash.4m.ld

I was not abler to check for other readers.

**Comment by omersiar** [comment]
2mb firmware, 2 mb spiffs allows us to make ota updates bigger than 550kb firmwares,  i think we can make the firmware small enough to fit in first 500 kb, but this requires multiple optimizations.

It must be a bug in the staging version of esp8266 core, it will be mature eventually.

**Comment by nardev** [comment]
Hey @omersiar, what do you think about making separate builds for different reader types? I assume that once you determine the reader type you would not change it for a while. And if you are developer, all readers version is ok for you, OTA would not be something importand if you constantly have the ESP on your table.

**Comment by omersiar** [comment]
We are working on different solution for OTA update.
I dropped using of staging version of Core
