### ISSUE TITLE
Websocket broken in version 7.5

### ISSUE THREAD

**Issue by wat32** [omersiar/esp-rfid#129]
I have a problem with connection via websocket in last version 7.5
v 7.5
wscat --auth admin:admin -c ws://door.domen.xx/ws
error: Unexpected server response: 401

v.7.3
wscat --auth admin:admin -c ws://door.domen.xx/ws
connected (press CTRL+C to quit)

Here is wscat version used (the last one)

wscat --version
2.2.1
npm install -g wscat

Also I tryed
wsc 
WebSocket client for the terminal

Or maybe there is a way how to connect the last version from the console?

**Comment by omersiar** [comment]
Did you try latest version? https://github.com/omersiar/esp-rfid/releases/download/0.7.6/firmware.bin

**Comment by wat32** [comment]
If I load this firmware in the interface I have version 7.5

**Comment by omersiar** [comment]
Ok, there is a problem with the latest release. I will prepare a new one

**Comment by wat32** [comment]
on 8.0 work , 8.2 broken again

**Comment by iBobik** [comment]
Also have it broken on 8.2.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (glyphicons-halflings-regular.woff2, line 0)
[Error] WebSocket connection to 'ws://192.168.4.1/ws' failed: Unexpected response code: 401
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
