### ISSUE TITLE
service of e.g. 10 systems (readers) on one website www

### ISSUE THREAD

**Issue by sargus123** [omersiar/esp-rfid#130]
Hello.
I apologize for the mistakes and not exactly the right place for questions.

is it possible to manage e.g. 10 layouts on one page so that you can manage where who has access?

because as an independent system I see many pluses and admire the vases for the effort to write it.

but if it were possible to centralize the management, it would be beautiful.

**Comment by omersiar** [comment]
With some serious scripting this can be done right now. But I cannot guarantee that there will multiple client solution.

**Comment by omersiar** [comment]
Closing it for now, we are working of client version of esp-rfid which will connect to a master node to check users
