### ISSUE TITLE
Official Hardware for ESP-RFID

### ISSUE THREAD

**Issue by omersiar** [omersiar/esp-rfid#133]
Thanks to @nardev now we have a 2 sided PCB board that carefully designed for your access control needs. Also we are working on some software bug fixes, a better MQTT scheme and optimized code base for the new hardware.

All credit goes to @nardev, he put great effort for making it. 

It can be purchased from tindie.com

https://www.tindie.com/products/nardev/esp-rfid-relay-board-12v-in-esp8266-board/

**Comment by nardev** [comment]
Thank you for this @omersiar 

Actually there is a new board with relay. It can be purchased here:

https://www.tindie.com/products/nardev/esp-rfid-relay-board-12v-in-esp8266-board/

There is also the detailed document about the board and short demonstration video.

Please check there.

Also, for all of you following this ESP-RFID repository of @omersiar i have 20% discount code for first 5 guys who buy the board: **4583389A**

**Video:**

[![IESP-RFID-RELAY-BOARD](https://img.youtube.com/vi/rXRt-YkzXZU/0.jpg)](https://www.youtube.com/watch?v=rXRt-YkzXZU)

**Image:**

![IESP-RFID-RELAY-BOARD](https://cdn.tindiemedia.com/images/resize/NEv5W7_GvxT8d4j-BWPDE5k-JQM=/p/full-fit-in/2400x1600/i/02868/products/2018-08-01T22%3A28%3A20.406Z-Untitledsd.jpg)

**Comment by koffienl** [comment]
Received my board today, thanks again @nardev !
The board looks very solid, nice job. Unfortunately I hadn't much time to play with it so I connected my 12V adapter to the main input and the reader to terminals on the right side. Very nice to see that there is a voltage regulator to power the ESP but also give the full power to the reader. I no longer have to make separate power sources to my project. Just hook up 12V and the ESP and reader get power.

The board came with ESP-RFID preloaded en preconfigured for the reader. Works out of the box.
I hope to give this board more time later this week.

Nardev did a great job designing this board!

**Comment by pistukk** [comment]
good evening sorry but I have a problem I just flash in nodemcu the firmware esp-rfid with a rfid rc522, everything went ok until I entered the settings and I changed the password from admin to another.
from that moment I can not get in anymore tells me incorrect password.
I tried to flash the firmware again but nothing. you know how to help me thanks

**Comment by nardev** [comment]
@pistukk this should be under new topic but just a short tip:
I'm pretty sure that you miss typed your password so you have some issues now
Also, you can "format" the SPIFFS and delete all previous config files...

**Comment by koffienl** [comment]
Received a second RFID Wiegand reader today. Hooked it onto the PCB/terminals and powered on. Worked without a glitch. Keypad and RFID recognized instantly.

**Comment by nardev** [comment]
Glad to hear that.

**Comment by benzino77** [comment]
@koffienl  could you please share the links to wiegand devices you are using (expecially those with a keypad)?  
Maybe there should be a reference list (with links and pictures) with devices which ware tested and works fine?

**Comment by nardev** [comment]
In my experience all those devices on eBay functioning in a same way.

They are usually made to work with cheap Chinese central units that control 4-16 devices at once, so they are pretty much all compatible.

Nothing fancy about that....

Check new readme for the board, there is a picture of a device that I used https://github.com/esprfid/esp-rfid-relay-board/blob/master/README.md

**Comment by nardev** [comment]
p.s. @benzino77 https://www.ebay.com/itm/Waterproof-RFID-125KHz-ID-EM-Proximity-Card-Keypad-Reader-Wiegand26-302/251243468721?epid=1671262106&hash=item3a7f4717b1:g:PkEAAOxy7odRzC67

**Comment by koffienl** [comment]
@benzino77 I use the one @nardev has linked and this one : https://www.ebay.com/itm/Weatherproof-EM-Proximity-keypad-125KHz-WG26-34-RFID-Access-Control-Card-READER/221253070476

**Comment by benzino77** [comment]
Thanks! 
Don't close this thread. Let people put links and information about other devices which works well with this great software.

**Comment by snizzleorg** [comment]
did anybody try this: https://www.amazon.de/gp/product/B073VFYQXM/ref=ox_sc_act_title_1?smid=A3W54BA3DYJGSB&psc=1

**Comment by omersiar** [comment]
@snizzleorg It should work with official board, i did not see any issue with the device. Interesting design.

**Comment by Melkske2404** [comment]
Possible to add another option to the esp-rfid?

Knx ip : when a good read tag, send a value to a knx group or better toggle a knx group address.

https://github.com/envy/esp-knx-ip

**Comment by nardev** [comment]
@Melkske2404 i don't know much about that.

btw. New ESP32 board deserve much more capable firmware. I think i should prolonged sale for February.2019.
