### ISSUE TITLE
PN532 support in 0.8?

### ISSUE THREAD

**Issue by noisufnoc** [omersiar/esp-rfid#135]
I'm trying to use a PN532 NFC reader with 0.8 running on a nodeMCU w/o much success.  The board comes up, I can log into the UI, but I cannot read a card/add a user.  I've read through some of the past issues that PN532 support is in master but is experimental.  Is this still the case as of the recent release?

**Comment by omersiar** [comment]
Did you upload the generic firmware? Can you test your PN532 module against other examples?

**Comment by noisufnoc** [comment]
yes, I'm using the generic firmware.  I'll be testing the module with other examples this weekend, thanks.

**Comment by omersiar** [comment]
You need to set it to work on SPI bus with dip switches on the module itself

**Comment by noisufnoc** [comment]
Switched dip switches to SPI bus, still no go.  Going to test with another device.

**Comment by omersiar** [comment]
I will try to test it with my module although PN532 is an advanced piece of chip and there are available not so great code for it.

**Comment by thunderace** [comment]
I have tried all interfaces with PN232/ESP8266 : 
* HSU : failed
* I2C : failed
* SPI : failed

But it's working with Software Serial HSU (SWHSU) with this library : https://github.com/elechouse/PN532

**Comment by noisufnoc** [comment]
my C isn't very strong, but is it possible to replace the library with the one you link to?

**Comment by thunderace** [comment]
@noisufnoc : No, it's a different interface, only 2 wires, RX and TX.
Il will make a PR with this interface

**Comment by noisufnoc** [comment]
cool, happy to test when you've got something out there.

**Comment by omersiar** [comment]
The problem is the every available library for PN532 is blocking, the only non-blocking, refactored and polished library is currently included one.

HSU may solve the problem, since we just getting the UID anyway.

**Comment by omersiar** [comment]
@thunderace Hello,

Are there any update on this?

**Comment by thunderace** [comment]
@omersiar Hello, no time for now, perhaps next week

**Comment by thunderace** [comment]
I'am sorry, but the actual code is really too far from my own version. 
@omersiar : why all these .esp files? Strange from my (old) developper point of view :)

**Comment by omersiar** [comment]
This is mainly because i am not a developer, the project started as non standart Arduino c++ project that evolved into something ugly to look at it.

Still learning c++ though, i choose .esp extension becuase compiler does not bother to compile them into objects then linking it. 

Think of them as code parts that we copy their content into main.cpp at compile time.

If you have it on your fork i can copy it to mine

**Comment by ozett** [comment]
can anybody confirm that the pn532 modules can be connencted "only" with i2c ?
only -> 2 pins: SDA+SCL?


thankx

**Comment by deviousbehaviour** [comment]
Hi there!
I just worked through some bugs using a NODEMCU and noticed that when I attempted to attach the SS pin on the PN532 to GPIO-15 there was a continuity error between GPIO-15 and GPIO-13. 

So as a solution, I changed the default SS pin to GPIO-0  (D3 on the board) and was able to solve the boot loop issue myself.

Not sure if this helps, but it was a problem that needed a solution.

**Comment by interbiznw** [comment]
> Hi there!
> I just worked through some bugs using a NODEMCU and noticed that when I attempted to attach the SS pin on the PN532 to GPIO-15 there was a continuity error between GPIO-15 and GPIO-13.
> 
> So as a solution, I changed the default SS pin to GPIO-0 (D3 on the board) and was able to solve the boot loop issue myself.
> 
> Not sure if this helps, but it was a problem that needed a solution.

This helped me as well with a Wemos D1 Mini. It would not boot using SS pin on gpio 15
