### ISSUE TITLE
Publish uid / access denied when creating new user

### ISSUE THREAD

**Issue by koffienl** [omersiar/esp-rfid#139]
When I create a new user in the 0.8.0 web interface, a mqtt message is published regarding a access denied:
````{"type":"access","time":1534332914,"isKnown":"false","access":"Denied","username":"Unknown","uid":"xxxx"}````
In the event log a ````Unknown rfid tag is scanned```` message is logged.

Maybe it is a good idea to look if the web interface is in 'add new user' state?

**Comment by omersiar** [comment]
This is not a bug but a feature :)

**Comment by omersiar** [comment]
We publish every scan to MQTT broker even it's known to be added to user list.  Currently this is low priority fix and i really do not know easy way to determine if the scan is for adding or not.
