### ISSUE TITLE
rfid rc522 password problem

### ISSUE THREAD

**Issue by pistukk** [omersiar/esp-rfid#144]
good evening sorry but I have a problem I just flash in nodemcu the firmware esp-rfid with a rfid rc522, everything went ok until I entered the settings and I changed the password from admin to another.
from that moment I can not get in anymore tells me incorrect password.
I tried to flash the firmware again but nothing. you know how to help me thanks

**Comment by omersiar** [comment]
You can flash empty binary with flash.bat if you are on windows. This will erase everything and you will be able to login again with "admin" password.

**Comment by pistukk** [comment]
can you explain me the procedure

**Comment by omersiar** [comment]
Use flash.bat if you are on Windows, first choose option 3 and when finished this time choose option 1.
