### ISSUE TITLE
Latching relay support 

### ISSUE THREAD

**Issue by Brahmah** [omersiar/esp-rfid#148]
Plz add latching relay support. (Basically means when rfid activates the relay, the relay stays active till rfid deactivates the relay)

**Comment by hasyalilah** [comment]
HI 
i try to add some code and modify to support latching relay. reader MFRC522 worked great.

file that i add new code firmware ver 0.8.2
1.main.cpp
2.rfid.esp
3.esprfid.js
4.esprfid.htm

here the look like
![3](https://user-images.githubusercontent.com/45688163/49728484-7c4ca000-fca5-11e8-843a-7e0266a02c5f.png)

here the code.
[latching.zip](https://github.com/esprfid/esp-rfid/files/2662794/latching.zip)


hope it will help

hasyalilah.

**Comment by omersiar** [comment]
Pull Request would have been better, thanks  anyway, i will review this and add it to v1

**Comment by donatmarko** [comment]
Pull request created by implementing the feature (#218)

**Comment by omersiar** [comment]
@donatmarko Thanks again.
