### ISSUE TITLE
Status Led and Buzzer compatibility

### ISSUE THREAD

**Issue by PierfrancescoElia** [omersiar/esp-rfid#150]
Hello everyone, I have a question about this awesome software.

I want to buy an RFID reader like [this](https://goo.gl/TpDXKG), and it has included also a led light and a buzzer.

Is it possible to implement status led light of the reader and the buzzer with the software?
It would be great.

Thank you, have a nice day! :smile:

**Comment by omersiar** [comment]
Actually official hardware already has the pin for both buzzer and led but the code is not ready yet.

**Comment by PierfrancescoElia** [comment]
Thank you @omersiar for the quick reply.

Do you have any idea about when this feature could be released?
I'd really happy to help, if needed! :smiley:

**Comment by omersiar** [comment]
Give it a bounty then maybe someone will code it quickly.

**Comment by omersiar** [comment]
https://www.bountysource.com/issues/62842028-status-led-and-buzzer-compatibility

**Comment by omersiar** [comment]
Implementing this is going to take a long time.  No need to keep this on Issue list, closing for now.
