### ISSUE TITLE
Connecting MFRC522

### ISSUE THREAD

**Issue by Blarppa** [omersiar/esp-rfid#154]
Hi,

I must be facing the same connecting problem as many before.

Can you give a more specific instructions on connecting the MFRC522 reader? I assume it needs power and ground in addition to the wires listed but was not sure. Maybe with pictures to be 100% sure.

My wiring should be fine but I end up stuck after first reboot. I have MFRC522 connected to ESP8266, then I flash the firmware and everything is good until I configure my hardware and upload changes. After this reboot the ESP8266 turns on the blue led and the Esprfid-network disappears and I have to re-flash the hole thing. I suppose this is the boot-loop thats been discussed.

Couple of times out of 50 I have managed to get back to the network & config just to realize the changes have gone back to factory settings. Ie. the reader is wiegand...

Thanks for this great project! As I get it working someday it should just what I need.

**Comment by teriall** [comment]
Try to configure AP, or connect to a WI-FI network. I had similar issue, when network wasn't configured, ESP8266 gets boot-loop.

**Comment by araziforum** [comment]
Hi. I have same problem. I tryed teriall's way than it works. Thx.

**Comment by omersiar** [comment]
@teriall You found the bug, now let me fix it, thank you.

**Comment by omersiar** [comment]
https://github.com/omersiar/esp-rfid/blob/stable/src/config.esp#L82-L87

**Comment by omersiar** [comment]
https://github.com/omersiar/esp-rfid/releases/tag/0.8.2

**Comment by PierfrancescoElia** [comment]
Hi everyone. I am having some troubles with the connection between the MFRC522 and a NodeMCU. 

Premise: I have tried the 522 with an Arduino Mega and I made a sketch to light up different leds with different cards: it works.

I have connected, as indicated, as follows:
SDA <=> D8
SCL <=> D5
MOSI <=> D7
MISO <=> D6
GND <=> G
3.3V <=> 3V

Attached you can find a screenshot of the Hardware Setting area.
![schermata 2019-03-08 alle 12 10 29](https://user-images.githubusercontent.com/8597934/54025639-6dd62d80-419b-11e9-96fe-bcbf6cc5730a.png)

I've tried many times, but the red led on the chip is on, but if I try to scan a card when I am in Users' page, nothing happens.

Thanks in advance! 😃

**Comment by msanchezt** [comment]
Be careful with the Chinese MFRC522 readers.. Had a lot of issues because
of them.

Marcel Sánchez

**Comment by PierfrancescoElia** [comment]
Hi @msanchezt, thank you fro your response! 😄 

I bought this in an Arduino Kit, so it shouldn't be defective.

Could you please confirm that my configuration is correct?
Thank you again.

**Comment by Pako2** [comment]
If I remember correctly, I also had problems when I chose GPIO15 as an SS pin.
Finally, I used the GPIO16.

**Comment by PierfrancescoElia** [comment]
@Pako2 Thanks for your suggestion, but same thing. No responses.

**Comment by Pako2** [comment]
Try to set the gain to the maximum.

**Comment by PierfrancescoElia** [comment]
Same thing. Any other suggestions? I've tried two MFRC522.

**Comment by omersiar** [comment]
Please consider that it might be also powering issue.

**Comment by msanchezt** [comment]
I use the same connections and works fine for me. As said, had a lot of
issues with 4 cheap MFRC522 boards, until I found the correct ones.

My MFRC522 board had the letters: "MH" at the top left (and C13 at the top
right). All the MFRC522 I bought with "MH" were not working correctly.

At the ens I bought this one and worked perfectly:
https://www.amazon.es/gp/product/B00QFDRPZY/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1



*Marcel Sánchez Toledano*



Missatge de Ömer Şiar Baysal <notifications@github.com> del dia dv., 8 de
març 2019 a les 15:31:

**Comment by Federbein0815** [comment]
Hi I have the same Problem. https://github.com/ingeninge/esp-rfid/releases/tag/1.3.3. THe reader works on the raspberry pi. I tried GPIO 15,16 but when I go to the User page, nothing happend when i scan a tag. Please help me.

SDA <=> D8
SCK <=> D5
MOSI <=> D7
MISO <=> D6
GND <=> G
3.3V <=> 3V
RST <=> RST

**Comment by beped** [comment]
Same problem here, i have tried another esp8266 like w1 wemos mini and nodemcu, same problem
