### ISSUE TITLE
No firmware.bin for 8.1 release

### ISSUE THREAD

**Issue by Daquaney** [omersiar/esp-rfid#155]
I noticed there's no firmware.bin or generic.bin for the new v8.1 release on your github, so as a result, I cannot flash my device. Am I doing something wrong, or did you just forget to put that there?

**Comment by Birdbrainuk** [comment]
Did you find the firmware.bin as I can't find it either.

**Comment by KhanTech786** [comment]
https://github.com/esprfid/esp-rfid/releases

here you go
