### ISSUE TITLE
pcb  ESP-RFID Relay Board 

### ISSUE THREAD

**Issue by roysbike** [omersiar/esp-rfid#156]
Thank you for your project. Could you download the source of the pcb(ESP-RFID Relay Board ) for self-production?

**Comment by omersiar** [comment]
I think the V2 board's source drawings and cad files are not readily available for now.  Also you may purchase just the pcb from @nardev directly if you ask him.

**Comment by omersiar** [comment]
https://github.com/esprfid/esp-rfid-relay-board
