### ISSUE TITLE
MQTT subscribe for remote open door

### ISSUE THREAD

**Issue by roysbike** [omersiar/esp-rfid#159]
Is it possible to add subscribe for remote door opening?

**Comment by omersiar** [comment]
Yeah totally, can you explain me how this would work? Is it safe? What if someone crafts special MQTT payload and opens the door?

**Comment by roysbike** [comment]
It is quite safe to add auth (login/password) for MQTT.  Maybe mqtt_client.subscribe("home/rfid/door/status");

**Comment by roysbike** [comment]
I would like to open the door remotely. Can eat still variants?

**Comment by omersiar** [comment]
How subscribe works? The broker send an UID then we check against it or the broker tells the open door? Then how do i know the message is authentic ?

**Comment by roysbike** [comment]
uid is not checked. Authentication passes at the level of mqtt by login and password. The idea is to make the remote door open button through mqtt. When you need to open the door a short distance or at a remote distance. I'm using the node-red mqtt link homebridge homekit

**Comment by koffienl** [comment]
> How subscribe works? The broker send an UID then we check against it or the broker tells the open door? Then how do i know the message is authentic ?

For that part you should rely on the security implemented by the owner. He should use a mqtt account with only read rights on the specific topic. No other accounts should have read rights to that topic. A second account (for publishing) should only have write rights to that topic.
A step higher in securiy is implementing SSL, but I'm afraid this would draw to much memory from the ESP to leave for the rest of the code/project.

**Comment by roysbike** [comment]
OK. Can then implement through a POST request?

**Comment by koffienl** [comment]
> OK. Can then implement through a POST request?

You can already open the door by sending a testrely command through the websocket

**Comment by omersiar** [comment]
I believe SSL encryption can be used also basic subscribe can be implemented, but i can not make a promise at this time.  We will see.  Closing it for now.

**Comment by GMFalka** [comment]
Is there any hope that this will be implemented in the near future? 
I want to buy the official package, but its a must to be able to remote open the door/relay via HomeAssistant (secure mqtt?)
