### ISSUE TITLE
Reopen #129 , after update to 8.2

### ISSUE THREAD

**Issue by wat32** [omersiar/esp-rfid#161]
Websocket autorization dont work , after update from 8.0 to 8.2

**Comment by omersiar** [comment]
Can you test with other clients too?  I can connect with a Chrome extension.

**Comment by omersiar** [comment]
Is this still an issue for you? Did you manage it to work with other clients?

**Comment by omersiar** [comment]
Closing it for now, feel free to open it up again if you still believe it is a bug.
