### ISSUE TITLE
RC552 doesn't work

### ISSUE THREAD

**Issue by OliverParoczai** [omersiar/esp-rfid#170]
Hey,
After about 40 minutes of trying to fix the bootloop, i finally connected the RC552 correctly to the NodeMCU V3, but it still doesn't work. (3.3V->3V, GND->GND, MISO->D6, MOSI->D7, SCK->D5, SDA(SS)->D8(GPIO-15)) I attached a picture of my wiring, if there is some problem with it. I use esp-rfid 1.8.2(the already compiled one from releases). I have tried 3 different NodeMCU V3s, 2 different RC552 modules, 5 different power supplies, 4 different RFID tags (Mifare, two keychain, two card). If there is something else i need to add, please send a reply.

![20181022_125008](https://user-images.githubusercontent.com/14364555/47289435-fabc8800-d5fa-11e8-8196-e557ac35149b.jpg)

**Comment by omersiar** [comment]
I did not understand, is it working or not?

**Comment by OliverParoczai** [comment]
I connected it correctly, but it doesn't work.

**Comment by omersiar** [comment]
Did you tried debug build?

**Comment by OliverParoczai** [comment]
Not yet, but trying it right now then

**Comment by OliverParoczai** [comment]
Still nothing, my config is below.

> {
  "command": "configfile",
  "network": {
    "bssid": "mywifibssid",
    "ssid": "mywifi",
    "wmode": 0,
    "hide": 0,
    "pswd": "mywifipwd",
    "offtime": 0,
    "dhcp": 0,
    "ip": "192.168.0.40",
    "subnet": "255.255.255.0",
    "gateway": "192.168.0.1",
    "dns": "192.168.0.16"
  },
  "hardware": {
    "readerType": 0,
    "wgd0pin": 4,
    "wgd1pin": 5,
    "rxpin": 2,
    "sspin": 15,
    "rfidgain": 32,
    "rtype": 1,
    "rpin": 4,
    "rtime": 400
  },
  "general": {
    "hostnm": "esp-rfid",
    "restart": 0,
    "pswd": "myesppassword"
  },
  "mqtt": {
    "enabled": 0,
    "host": "",
    "port": 1883,
    "topic": "",
    "user": "",
    "pswd": ""
  },
  "ntp": {
    "server": "pool.ntp.org",
    "interval": 30,
    "timezone": 0
  }
}

**Comment by omersiar** [comment]
I need to see the init message of rc522

**Comment by OliverParoczai** [comment]
Is there a way to easily see it with the esp-rfid firmware or do i need to flash another one?

**Comment by omersiar** [comment]
You need debug.bin or pio run -e debug

**Comment by OliverParoczai** [comment]
Okay, doing it right now

**Comment by OliverParoczai** [comment]
So i just need to use a serial monitor or connect to it the regular way?

**Comment by omersiar** [comment]
pio -e debug -t monitor

Or

pio device monitor ?

**Comment by OliverParoczai** [comment]
All i get is "Error: no such option: -e"

**Comment by omersiar** [comment]
I do not remember correct parameter, you should find it.

**Comment by OliverParoczai** [comment]
Got it

> [ INFO ] Trying to setup RFID Hardware
[ INFO ] RFID SS_PIN: 15 and Gain Factor: 32
[ INFO ] MFRC522 Version: 0x0 (unknown)
[ WARN ] Communication failure, check if MFRC522 properly connected

**Comment by omersiar** [comment]
Hmm, change your SS pin and try again, also connect rc522's vcc pin to 5v, try different ribbon cables, try with better micro usb cable, if you have an Arduino or compatible board also try your rc522 boards with arduino as well

**Comment by OliverParoczai** [comment]
Changing the SS pin did the trick, now it works. Thanks for the help! Changing the VCC pin to 5v didnt let the ESP start

**Comment by omersiar** [comment]
Glad that it worked. Maybe all nodemcus are suffering from this issue.

**Comment by afandino1235** [comment]
what in did you use. I am having the same issue with a wemos

**Comment by OliverParoczai** [comment]
Did you connect all the pins correctly? 
Try SDA->D1, 3.3V->3V, GND->G, SCK->D5, MISO->D6, MOSI->D7 and then set the SDA pin to D1 inside the web UI.
I don't have a working WeMos board right now, so i cannot do any testing on that.
![Connection](https://i.imgur.com/8esSiR1.jpg)
