### ISSUE TITLE
Can't build it...

### ISSUE THREAD

**Issue by nardev** [omersiar/esp-rfid#18]
I tried to build it, installed all required libs but i got this error.

```
src/main.cpp:317:14: error: 'class ESP8266WiFiClass' has no member named 'scanNetworksAsync'
WiFi.scanNetworksAsync(printScanResult, true);
```

Any idea what could be an issue?

p.s. Also after commenting that line:

```
lib/ESPAsyncWebServer/src/AsyncWebSocket.cpp:40:18: fatal error: Hash.h: No such file or directory
#include <Hash.h>
```
Any idea???

**Comment by omersiar** [comment]
You need git version of esp8266 arduino core

**Comment by rneurink** [comment]
You need to have the latest esp arduino package and you don't have that one

Op 8 sep. 2017 3:46 p.m. schreef "nardev" <notifications@github.com>:

**Comment by ersinpw** [comment]
Where did you place the git version of the esp8266 Arduino core?

Mine is located here (osx): 
` /Users/ersin/Library/Arduino15/packages/arduino/hardware/esp8266com/esp8266/`
I guess it is the correct path according to the manual:
https://github.com/esp8266/Arduino#using-git-version
but fortunately I still see the same error
