### ISSUE TITLE
Add more protocols, not only MQTT

### ISSUE THREAD

**Issue by bib2** [omersiar/esp-rfid#180]
Hi, would it be possible to add more protocols for connectiong to a homeserver? I don´t use MQTT in my environment. It would be great, if i can use simple http-get-requests for this...

I´m using openhab as smarthomecontroller and if i enter this in my browser, i can send a command to my server:
http://192.168.1.1:8080/classicui/CMD?My_Switch=OFF

Here is some information:
https://community.openhab.org/t/how-to-change-an-openhab-switch-with-http-commands/35063/7

**Comment by omersiar** [comment]
We have websocket api (not n exact api but kinda api) that you can use.  You need to explore the commands on source files since we do not have documentation right now.

**Comment by bib2** [comment]
Ok, thanks a lot. Will there be a documentation some time or is this only a hidden function for testing?

I will try this. I´ve seen in openhab-forum, that it would be possible to communicate with websockets.

**Comment by omersiar** [comment]
The websocket communication is only for bi-directional communication between web browser and the actual device,  it will not be useful for any other use case, for example there is no easy way to get scanned rfid tags' id other than using mqtt.

I do not know how are you going to use it, so it may be limited for you, do not expect it to be a replace for mqtt.
