### ISSUE TITLE
WaitReady () -> TIMEOUT (when PN532 reader is selected)

### ISSUE THREAD

**Issue by Pako2** [omersiar/esp-rfid#190]
The PN532.cpp library contains the following snippet:
```
bool PN532::WaitReady() 
{
    uint16_t timer = 0;
    while (!IsReady()) 
    {
        if (timer >= PN532_TIMEOUT) 
        {
            Utils::Print("WaitReady() -> TIMEOUT\r\n");
            return false;
        }
        Utils::DelayMilli(10);
        timer += 10;        
    }
    return true;
}
```
As a result, the **WaitReady () -> TIMEOUT** message is very often listed in the serial monitor.
This is very annoying, and I propose the corresponding part (one single line) in the library **to comment**.

**Comment by omersiar** [comment]
I have PN532 lying around somewhere, actually it need to be tested more.

- [ ] Test PN532
