### ISSUE TITLE
Relay Type inversion

### ISSUE THREAD

**Issue by Pako2** [omersiar/esp-rfid#191]
I think the **Relay Type** parameter works **inversely**.
For example, the "**Active High**" value means that in the idle state, there should be (on the appropriate pin) the **LOW state**. But it is not. It's reversed.

**Comment by omersiar** [comment]
I can give you write access to repo if you want, you can make changes as like as you want.

**Comment by Pako2** [comment]
I thank you for your trust, but I do not want it.
This is too much responsibility.
For your information: I have never made a pull request until now.
I'm just learning to work with GitHub. This is my first collaboration on a project ...

**Comment by omersiar** [comment]
Thank you for the PRs and for the bug hunting.
