### ISSUE TITLE
I am also not able to connect to wifi after installing new firmware, working great with 08.2

### ISSUE THREAD

**Issue by tipsworld** [omersiar/esp-rfid#195]

**Comment by tipsworld** [comment]
When you install 0.9.0 and setup WiFi then save it, when the ESP restarts it is still in AP mode 
I can use in AP mode, but not in clientmode

**Comment by Bojan505** [comment]
new version 0.9.0  does not work correct. When I want to configure the program as a client. When  press the <Scan> key, it does not enter the available  wifi networks. If I enter the parameters manually, they does not save changes.

**Comment by omersiar** [comment]
Please see https://github.com/esprfid/esp-rfid/issues/192#issuecomment-441244852
