### ISSUE TITLE
Webinterface update still shows "latest version 0.8.1" - Is there a ready-to-use firmware-update-file for 0.9.0?

### ISSUE THREAD

**Issue by bib2** [omersiar/esp-rfid#197]
Hi, where can i download the new 0.9.0.bin - file for update with webinterface? The webinterface still shows "latest version 0.8.1", but my new buyed esp-rfid-controller is already 0.8.2.

I know this link: https://github.com/esprfid/esp-rfid/releases/download/0.9.0/esp-rfid-0.9.0.tar.gz

But which file do i have to use for webinterface update?

esp-rfid-0.0.0.tar.gz
esp-rfid-0.9.0.tar-1
blank4mb.bin
forV2Board.bin
or
generic.bin
???

And another small error: I think only a typo:
I get this messages over mqtt: '{"type":"hearthbeat","time":1542871009}'

Shouldn´t it be heartbeat without the "h"?

**Comment by omersiar** [comment]
There is a bug with the 0.9.0 and 0.8.2 releases, I rolled back to latest release to 0.8.1.

You should wait for the bug fix release (0.9.1) which is currently not available.
