### ISSUE TITLE
ESP8266 12E v0.9.0 can not save change and restart to connect to a wlan

### ISSUE THREAD

**Issue by K7cl** [omersiar/esp-rfid#198]
i use esp8266 12e and rc522. every thing going well with v0.8.2. i try to update to v0.9.0 by erase all and flash or update from v0.8.2. both two way got same problem in connecting to wifi. i configure the wlan setting but it no respond when i select "save change and restart", and it will still in AP mode.

**Comment by omersiar** [comment]
v0.9.0 is not ready yet.
