### ISSUE TITLE
Add user in mqtt

### ISSUE THREAD

**Issue by ccfiel** [omersiar/esp-rfid#200]
Is it possible adding user using mqtt or and api?

**Comment by omersiar** [comment]
You can use websocket commands to use add user, you need to look into source files since we do not have documentation for it.

**Comment by nardev** [comment]
New approach for communication with device should be introduces. I hope for 1.0.

Before that, we should figure out how to protect writing to a device through mqtt and http API. there should be some API key exchange and some kind of identifying approved clients.

just isolating mqtt and http in controlled and protected networks doesn't look safe enough for me.

**Comment by ccfiel** [comment]
@nardev I think generated token value in the server side and display the value in the website and used it in the client api side would be enough for the security in accessing the api.

**Comment by omersiar** [comment]
I will improve websocket API and its documentation.
