### ISSUE TITLE
Nodemcu - RC522 doesnt detect any tags

### ISSUE THREAD

**Issue by GMFalka** [omersiar/esp-rfid#203]
I just cant get it to detect any tags...

I zealously checked all closed issue on this (there were a few), all had missplaced wires. I quadro checked the wiring, tried different wiring, different nodemcu and wemos mini. 

If i use a very simple arduino ide code for mfrc522, it DOES detect the tags.

Where is my fuckup? :(

![image](https://user-images.githubusercontent.com/17993825/49555232-79e1f300-f8ff-11e8-84bd-b015e8a1ac8c.png)

**Comment by GMFalka** [comment]
This is the code that does work, if its any help.

```
#include "MFRC522.h"
#define RST_PIN  5 // RST-PIN for RC522 - RFID - SPI - Modul GPIO5 
#define SS_PIN  4 // SDA-PIN for RC522 - RFID - SPI - Modul GPIO4 
MFRC522 mfrc522(SS_PIN, RST_PIN); // Create MFRC522 instance


void setup() {
  Serial.begin(9600);    // Initialize serial communications
  SPI.begin();           // Init SPI bus
  mfrc522.PCD_Init();    // Init MFRC522
}


void loop() { 
  // Look for new cards
  if ( ! mfrc522.PICC_IsNewCardPresent()) {
    delay(50);
    return;
  }
  // Select one of the cards
  if ( ! mfrc522.PICC_ReadCardSerial()) {
    delay(50);
    return;
  }
  // Show some details of the PICC (that is: the tag/card)
  Serial.print(F("Card UID:"));
  dump_byte_array(mfrc522.uid.uidByte, mfrc522.uid.size);
  Serial.println();
}

// Helper routine to dump a byte array as hex values to Serial
void dump_byte_array(byte *buffer, byte bufferSize) {
  for (byte i = 0; i < bufferSize; i++) {
    Serial.print(buffer[i] < 0x10 ? " 0" : " ");
    Serial.print(buffer[i], HEX);
  }
}
```

**Comment by GMFalka** [comment]
So theres a definitive bug, if i dont setup the wifi before first reboot, it WILL bootloop.
Still doesnt recognize any tags in webui  :(

**Comment by romanzava** [comment]
Hi,

same problem here with the latest version 0.9.0.
Tried wiegand rfid, MFRC522 but still without any tag validated.

**Comment by GMFalka** [comment]
I tried multiple versions, no tag detection :(
It might be a problem with the software rst pin?
The simple arduino code does use the rst pin and it works.

**Comment by kogomonier** [comment]
Same issue for me. All setup but no RFID recognition possible :( Any suggestions?
![img_20181214_195721](https://user-images.githubusercontent.com/45883400/50021871-b33ef080-ffda-11e8-9225-a88a5ecd75e7.jpg)

**Comment by DuschdrBabbe** [comment]
Same problem here...

In the pinout description for RC522 sck goese to D4/D5 must i connect both? Or just one of them?

What can i do to help to fix this?

**Comment by gabtnimed** [comment]
just read the id of the cards with a simple code and an arduino card then add one of the cards manually
  through the graphical interface. the others will be added automatically by a simple scan

**Comment by DuschdrBabbe** [comment]
thx now it*s running

**Comment by Birdbrainuk** [comment]
Have you got the firmware you upload to the nodemcu.  I can't find it.

**Comment by DuschdrBabbe** [comment]
Have used the 0.8.1 you can find here 
https://github.com/esprfid/esp-rfid/releases

https://github.com/esprfid/esp-rfid/releases/download/0.8.1/esp-rfid-0.8.1.tar.gz 

Inside These gz are all files

**Comment by afandino1235** [comment]
The issue for me was that it took changing the ant gain setting and it starts working.
