### ISSUE TITLE
Adding status leds: ON/OFF/reading

### ISSUE THREAD

**Issue by msanchezt** [omersiar/esp-rfid#206]
It would be great to add 3 leds in order to display alarm status.

Just as an example:
- OFF: red led
- ON: green led
- ARMING alarm (pending): blinking green 
- Reading: blue led

I don't know where to start with. Is this even possible with this project? Any thoughts?

**Comment by nardev** [comment]
Buzzer and Led special statuses will be added soon. I hope before 31.12.

**Comment by msanchezt** [comment]
Thanks for the answer. Is that something you ore anyone else on the team is working in?

Because I just saw another threat requesting same feature as me, and it was closed by a colleague, basically saying this is not in the roadmap.
