### ISSUE TITLE
Missing firmware.bin

### ISSUE THREAD

**Issue by Birdbrainuk** [omersiar/esp-rfid#207]
I can't find the firmware in the 8.1 download.

Seems this has been seen before as there are a couple of closed issues which makes me think it's just me. But the don't say if they found it and if so where.

Help appreciated.

**Comment by DuschdrBabbe** [comment]
https://github.com/esprfid/esp-rfid/releases/download/0.8.1/esp-rfid-0.8.1.tar.gz

**Comment by kishorerabha** [comment]
my board is a V3. which option should i select? btw no matter which one i select, it wont flash.

**Comment by Erdccc** [comment]
RaiderXXL,
I down loaded your 0.8.1 link as mentionned above, but it does not contain the file named firmware.bin that DrZZs talks about in his youtube about your software. Could you please post a direct link to it?
`https://www.youtube.com/watch?v=ENMul9eAB00&t=326s'

Thank you

**Comment by DuschdrBabbe** [comment]
![5643524c-58c9-413e-9d14-a31d1ed30070](https://user-images.githubusercontent.com/34094049/50549627-4ecd9380-0c60-11e9-9ba1-2d818ded021b.jpeg)


Just use generic.bin .... i have used it for my nodemcu

**Comment by KhanTech786** [comment]
https://github.com/esprfid/esp-rfid/releases

here you go
