### ISSUE TITLE
Search 8.1 with rdm6300 support and mqtt

### ISSUE THREAD

**Issue by Tiefflieger1** [omersiar/esp-rfid#209]
Search 8.1 with rdm6300 support and mqtt. Just do not get an image created for flashing. Always error message. Can someone help me ? am desperate ;-)

**Comment by Tiefflieger1** [comment]
Or the 9.0 ;-) Have the RDM6300 currently involved and he also reads the uid but in mqtt he just does not save me the setting under Topic. I would be very grateful

**Comment by omersiar** [comment]
Please try latest release candidate version and open if it is not working for you.
