### ISSUE TITLE
Can't build esp-rfid

### ISSUE THREAD

**Issue by ersinpw** [omersiar/esp-rfid#21]
Similar to issue #18 

Where did you place the git version of the esp8266 Arduino core?

Mine is located here (osx):
/Users/ersin/Library/Arduino15/packages/arduino/hardware/esp8266com/esp8266/
I guess it is the correct path according to the manual:
https://github.com/esp8266/Arduino#using-git-version
but unfortunately I still see the same error

**Comment by omersiar** [comment]
I do not use mac, maybe @rneurink may help on this.

**Comment by rneurink** [comment]
One of my testers has a mac but i haven't been building on it. If you go
into the arduino settings and put the url in additional board manager. You
are able to select the right version for the arduino core in the library
manager

**Comment by jugs695369** [comment]
Plz provide working video or detailed operation of process
