### ISSUE TITLE
MQTT disconnected after 2 minutes

### ISSUE THREAD

**Issue by donprosko** [omersiar/esp-rfid#213]
Version 0.8.1 on Lolin NodeMCU V3 with RFID RC522 and mosquitto version 1.5.5.
after about 2 minutes no MQTT messeages come to the broker but the mosquitto log don't recognize a disconnection. According the esp_rfid log the RFID reader works fine.

**Comment by omersiar** [comment]
Please try latest release candidate and open this issue again if you have problem with it.
