### ISSUE TITLE
Avoiding nfc tags cloning

### ISSUE THREAD

**Issue by jmvaz** [omersiar/esp-rfid#214]
There is any security system implemented in esp-rfid?

If not, I can recommend 2 approachs to avoid NFC tags cloning:

1- wipe the sector 0 

> If you will, to make this as guaranteed as possible with this kind of technique, you could try the following:
> - Write to Sector 0, block 0, wiping the UID;
> - If this succeeds, you have a cloned card, and as a side advantage, the card is disabled ;)
> - If this fails, you can read the UID and check against your data.
in : http://forum.arduino.cc/index.php?topic=286447.0

2 - Using nfc writable tags and keeping one shared sequence between the tag and the esprfid. 
Everytime that the tag is readed the sequence is increased.

Waiting your feedback,

Regards,

**Comment by omersiar** [comment]
This is interesting, i will keep it in my mind.  Implementing it will be hard so not going to happen any time soon.
