### ISSUE TITLE
feature request: timeslot vor valid key (08:00-13:00)

### ISSUE THREAD

**Issue by ozett** [omersiar/esp-rfid#215]
make an option for a daily timeslot, 
in wich the key is valid, ie.: (08:00-13:00)

and/or make also days valid:
i.e:
(MO-FR 08:00-13:00)
(SA,SU 08:00-13:00)
(TUE,FR,08:00-13:00)

**Comment by omersiar** [comment]
This is still in my To Do list since version v0.2. 🤷‍♂️

**Comment by evazzoler** [comment]
I follow, I'm really interested. This make sense to having a NTP more than log accesses.
Please, contemplate a substantial number of available timeslots.
