### ISSUE TITLE
PN532 with I2C (SDA/SCL)?

### ISSUE THREAD

**Issue by ozett** [omersiar/esp-rfid#216]
i thought of making a [new request](https://github.com/esprfid/esp-rfid/issues/135#issuecomment-451691728).

as the [adafruit lib](https://learn.adafruit.com/adafruit-pn532-rfid-nfc/arduino-library) has it in, 

  ![image](https://user-images.githubusercontent.com/5937811/50734777-75318880-11a4-11e9-83d4-4aa1e4f0cbd0.png)

i cannot see why your wonderful approach could not support pn532 with i2c.

but as far as a non-coder can see, you have hardcoded the SPI-Interface.

![image](https://user-images.githubusercontent.com/5937811/50734778-811d4a80-11a4-11e9-89b6-916d1f375386.png)

can you make pn532 wit i2c possible?

**Comment by ozett** [comment]
so sad 😢  that this did not make into v1.0 😢

**Comment by orientalsniper** [comment]
If you don't want to wait, you can use ESPEasy.

**Comment by ozett** [comment]
> If you don't want to wait, you can use ESPEasy.

i am already running ESPeasy and want to switch to this here.
to run a single instance with this superb gui and this cool standalone user-managment.
(maybe also with a timer for valid opening times - in v1.1?)
😄

**Comment by omersiar** [comment]
Originally the idea was running both RC522 and the PN532 at the same time, so i have chosen SPI bus. It can be done with I2C too.

**Comment by ozett** [comment]
i am glad you have it on the list.
i2c is available on all pn532-boards, simple to wire.
but be aware of what the coders call somhow "i2c clock strech"-issue. 
on tasmota source there is a fix(?) coded, i believe. it seems dpend also on the esp-sdk-version.
may you have a look sidedways to save some time ? https://github.com/arendst/Sonoff-Tasmota/issues/2915#issuecomment-451662727
than it can be quickly implemented, i guess
😸
