### ISSUE TITLE
Implement some changes

### ISSUE THREAD

**Issue by Maik2016** [omersiar/esp-rfid#217]
Hello,

I have changed the 0.8 version to  2 new functions like   close and ring because my code lock also submits the ring command via wiegand.  
Also i found out, that there is no max retry limit available that makes brute force relay easy.
I also implemented the max retry with a blocking of the communication.
The coding is not finished ( not nice looking and not changeable through the WEB Interface as of now)  but works for now :D   If this is interesting I can try to upload the changes ( have to figure out how to do this)
Also I try to put this in the source code for 1.0 beta

**Comment by omersiar** [comment]
2 seconds cool down between succeeding scans is just enough for mitigating the brute force attack.

**Comment by omersiar** [comment]
@Maik2016 Any update on this?

**Comment by Maik2016** [comment]
I have no update due to some work issues and traveling a lot :(  No time to look at it again. But end of next week I'm back home and hopefully have some time, I have to check what has changed in the source code till now.

**Comment by omersiar** [comment]
@Maik2016 I'm preparing milestones for the v1.5, if you can just publish your changes through a fork or direct copy paste, community can work on it, no need to wait for polishing it.

**Comment by Maik2016** [comment]
I createt a fork I hope this works, was the first time I used GitHub uploaded the src Folder new

**Comment by omersiar** [comment]
Thanks for your contribution to the esp-rfid, much appreciated.
