### ISSUE TITLE
security issue of websocket

### ISSUE THREAD

**Issue by simoncheen** [omersiar/esp-rfid#22]
hello, 
we found a security issue of the websocket.
```step 1. ```
 http://www.websocket.org/echo.html
fill 
```bash
ws://ip_address/ws 
```
and click connect.

```step 2.```
fill 
```bash
{"command":"getconf"}
``` 
in the message text box , and click "send" button. 

wow, you would get the password

**Comment by omersiar** [comment]
Also you can delete a known Users, change configuration, etc. Simply WebSocket communication is not secured at all. See [ToDo](https://github.com/omersiar/esp-rfid#to-do) list. I should definitely mention this at Known Issues level. Thank you.

**Comment by simoncheen** [comment]
I'm try to change the websocket as this https://github.com/Links2004/arduinoWebSockets , it seems have basic Authorization

**Comment by omersiar** [comment]
See https://github.com/me-no-dev/ESPAsyncWebServer/pull/272

**Comment by simoncheen** [comment]
perfact !
