### ISSUE TITLE
1.0.0-rc1 but bin is 0.9.4 ?

### ISSUE THREAD

**Issue by DuschdrBabbe** [omersiar/esp-rfid#221]
Hi,
i downloade the new release and inside the bin ist version 0.9.4 is this correct?

greetings...

Pascal

**Comment by msanchezt** [comment]
Same "issue" here.

I upgraded via web from 0.9.1 to 1.0.0-rc1 but instead it says version running is 0.9.4

**Comment by omersiar** [comment]
This is why it is a release candidate. Thanks for reporting.
