### ISSUE TITLE
after a while the RFID reader stops

### ISSUE THREAD

**Issue by donprosko** [omersiar/esp-rfid#223]
1.0.0-rc1 (or better 0.9.4) on Lolin NodeMCU V3 with RFID RC522 and mosquitto version 1.5.5.
now MQTT messeages seem to be fine but after a while (sorry, don't know how long) the RFID reader stops. There is no reaction, no log entry and no line in there serial debug protocol. After a hard reset it works again until the next break.

**Comment by araziforum** [comment]
I have same problem. I will try my chance with 0.9.4

**Comment by omersiar** [comment]
There is no 0.9.5, and the version number is just a text, does not mean that the firmware does not include fixes.

Can you please give more details?

Is esp not responsive?

Can you login webui while rfid is not working?

**Comment by araziforum** [comment]
Hocam web arayüzüne erişim oluyor ancak rc522 kart okumuyor. rc522nin güç lambası yanıyor ama hareket yok. Gücü kesip geri verince düzeliyor ama bir süre sonra yine aynı duruma geliyor. Ben 0.9.4 e geri döndüm öyle deniyorum. (0.9.5 i hata ile yazmışım düzelttim)

**Comment by araziforum** [comment]
Wemos d1 i değiştirdim olmadı, rc522 yi değiştirdim yine olmadı. Donanım arızasının olmadığını kesinleştirdim ama sorun nedir bilemiyorum

**Comment by donprosko** [comment]
The esp is full reachable with HTTP and everything seems to work. Only the reader is dead.

**Comment by omersiar** [comment]
Then it may be a library issue. I will check the mfrc522 repo.

**Comment by donprosko** [comment]
thank you

**Comment by marceltech** [comment]
I'm facing the same problem, it seems that only sensor stop to work! I'm using RFID -RC522. Does it work with wiegand (https://pt.aliexpress.com/item/Boa-Qualidade-ZK-KR202E-Leitor-de-Cart-o-de-Controle-De-Acesso-RFID-Wiegand26-Leitor-de/32874980628.html) using password instead of rfid sensor?

**Comment by marceltech** [comment]
Dear Colleagues, Just to add more details, the heartbeat mqtt message still receving that's make sense what Omer told, looks some issues with library.

**Comment by donprosko** [comment]
maybe it makes sense to use the RST Pin of the RC522 again? Or if the RC522 itself works fine we can use the IRQ pin and trigger the ESP?

**Comment by omersiar** [comment]
Can you guys test this https://github.com/esprfid/esp-rfid/releases/tag/1.0.1

**Comment by omersiar** [comment]
@marceltech Keypad entry is not supported at this time, but community working on it.

**Comment by araziforum** [comment]
I'm testing. 40mins passed, still working fine.

**Comment by araziforum** [comment]
2 hours, 40 mins passed still working. I think problem resolved. I will try it until next day.

**Comment by donprosko** [comment]
Thank you Ömer. I've alread flashed the ESP with v1.0-hotfix1. after about 15 minutes the I rcognized no reaction on any RFID chip. So I seems form me the same behaviour as with 1.0.0-rc1.

**Comment by omersiar** [comment]
Which rfid readers do you have?

**Comment by donprosko** [comment]
the RFID RC522 from AZ-Delivery (only SPI mode possible).
So I set in Hardware Settings Reader Type = MFRC522.

**Comment by marceltech** [comment]
> Can you guys test this https://github.com/esprfid/esp-rfid/releases/tag/1.0.1

Looks good now! Thanks!

**Comment by araziforum** [comment]
16 hours, 9 mins passed works fine. Now I will cut the power and try to test again.

**Comment by donprosko** [comment]
I asume I have troubles with the SPI bus. The RC522 should be outside of the house and the ESP inside. So nobody can manipulate the relay PIN from outside of the house. 
The SPI cable length have to be about 30 cm. That's a lot for the SPI clock speed of ...
#define MFRC522_SPICLOCK SPI_CLOCK_DIV4			// MFRC522 accept upto 10MHz
Is it possible to slow down the SPI clock speed to increase the SPI bus stability?

**Comment by omersiar** [comment]
spi speed was hard coded to mfrc22 library, i guess changing it is just newly introduced.

you should try it yourself, cherry-pick the commit and set esp's speed as well.

**Comment by 78Ronin78** [comment]
How run project without device? I run web emulator, run localhost and get message: "Upgrade Required". How fix it?

**Comment by donprosko** [comment]
THX Ömer, I will try it in the evening. 

FYI: with the short cable of 10 cm it seems to work better. since about 8 hours I have no RC522 breakdown.
So maybe we should close this issue because slowdown SPI clock speed is a feature request in another context. Isn't it?

**Comment by omersiar** [comment]
You just need admin rights.

**Comment by omersiar** [comment]
It's outside of the esp-rfid, unless mfrc522 library makes spi speed choosable.
