### ISSUE TITLE
Can't get the keypad working

### ISSUE THREAD

**Issue by ciscogomes2001** [omersiar/esp-rfid#228]
I have this wiegand keypad https://www.ebay.com/itm/125KHz-Wiegand-26-RFID-Card-Keypad-ID-EM-Reader-For-Door-Access-Control/182533684678?hash=item2a7fdafdc6:g:ajoAAOSwcdRY9JBu:rk:31:pf:0 and i can't get the pin in the user settings. running v1.0.0. Can anyone help me?

**Comment by nardev** [comment]
Please explain bit more, how did you connect it, what did you connect?
