### ISSUE TITLE
config Settings

### ISSUE THREAD

**Issue by mekodak** [omersiar/esp-rfid#238]
Hi

I am not able to change the Wi-Fi to Client,
When i try, and hit save.
I try to find it on my network, but nothing to find,
then i restart the power to the unit and check again, but still nothing to find.

And when i login to the unit as AP the settings is reset.

And i have tryed to use the "Test" button for the Relay test and nothing happens.

**Comment by omersiar** [comment]
Hi,

Do you able to get information on status page? Which browser do you use?

**Comment by mekodak** [comment]
It was no matter witch browser i used,
yes i was able to se the "Status site".

In Internet Explorer was i able to use the "test" button but when i pressed it it did not turn off again.

But the fail was that i was not able to scroll bovn om the "Modal Box" and i did not know that ther was a "Save & Reboot" button at the buttom.
But i did just Mark all the "Modal Box content" then it showed.

**Comment by mekodak** [comment]
And by the way can i get a GPIO pinout of the board??

**Comment by mekodak** [comment]
Some thing like:
![rfid pinout](https://user-images.githubusercontent.com/32038595/52145916-9af66400-2662-11e9-8685-b80899f0eaab.png)

**Comment by nardev** [comment]
@mekodak  In fact, there is more in the docs here: https://github.com/esprfid/esp-rfid-relay-board

**Comment by mekodak** [comment]
https://github.com/esprfid/esp-rfid-relay-board#relay
says that GPIO13 is used for relay, but how can it then be used for
MOSI (& for "D0") ("https://github.com/esprfid/esp-rfid#pin-layout")

And https://github.com/esprfid/esp-rfid-relay-board#reader-9-pin-terminal says that "D0" is GPIO4
I am a bit confused.

I want to test out with a "MFRC522".

**Comment by omersiar** [comment]
You can not use mfrc522 with official hardware it is just for wiegand readers and wiegand bus is not Spi so there is no Mosi Miso

**Comment by mekodak** [comment]
So the software is build for "MFRC522" without the board (only wit ESP8266)

**Comment by omersiar** [comment]
Closing it for now, if you need additional help please open a new one.
