### ISSUE TITLE
unable to change reader type

### ISSUE THREAD

**Issue by trudeau102000** [omersiar/esp-rfid#239]
on the settings- Hardware Settings the reader type-Pin D0-Pin D1 and Relay Pin cannot be changed
![image](https://user-images.githubusercontent.com/47269899/52162359-cef07a00-26a0-11e9-88fb-9de42dc3c015.png)

**Comment by trudeau102000** [comment]
I have tried it on chrome, firefox, IE and android same result

**Comment by omersiar** [comment]
When you flash forv2board.bin this is the expected behaviour.

If you do not have official board please use generic.bin

**Comment by trudeau102000** [comment]
when ever i try to flash generic.bin instantly it pops up flash complete but nothing flashes to the module. any ideas?

**Comment by trudeau102000** [comment]
the esp shows up on com3

**Comment by trudeau102000** [comment]
i am suspecting either the esp or the cable. new ones on the way

**Comment by trudeau102000** [comment]
its odd how the esp runs and access is fine with the forv2board.bin firmware except for the setting issues

**Comment by omersiar** [comment]
it's same beside you do not need those settings on official hardware

**Comment by trudeau102000** [comment]
guess I will just throw in the towel. i got a couple more esp's and some new cables and just ended up with  new issues. after uninstalling and reinstalling the driver i can now flash the firmware but after flashing it to probably 6 different ones its just one hurtle after another. now i can get the esprfid ap and connect but it don't matter what esp i do once i enter the wifi ssid a pass- save and commit using dhcp thats it. i can never connect to it again. no ap to connect to again and never connects to my wifi. after several days on this i'm done. wish i could remember what firmware i flashed the very first time because that one seemed to work and was pretty stable.

**Comment by trudeau102000** [comment]
i now have it connected to my network and seems stable. i will be getting a couple new rc 522's tomarrow so i can continue. the only issue i have now is getting my relay functional i have it connected to gpio 14 but unable to get ti trigger with the test button. i can  trigger the relay manually by pulling the relay pin low or high

**Comment by trudeau102000** [comment]
![20190204_180923](https://user-images.githubusercontent.com/47269899/52243724-899e9900-28a8-11e9-8109-e2cda6b144d9.jpg)
prob could have just went with the official hardware in the first place.and i will when i know this is going to work

**Comment by trudeau102000** [comment]
6 esp8266 and 5 rc522's. 6 days and was able to get it to work once. I can hook the rc522 to my nano, uno or mega and read tags all day. perhaps someone can post a firmware.bin that they got to work on a esp8266 module

**Comment by omersiar** [comment]
Can you please download fresh 1.0.2 and delete forv2board.bin then rename generic.bin to forv2board.bin and then use flash.bat then chose option 2

**Comment by trudeau102000** [comment]
I now have this working but the issue seems to be with the gain for therc522. if i select max 48db in hardware settings what should it show in the config for "rfidgain"?

**Comment by trudeau102000** [comment]
![gain1](https://user-images.githubusercontent.com/47269899/52309132-2e82aa00-296d-11e9-97fb-0f7856f89438.png)
![gain2](https://user-images.githubusercontent.com/47269899/52309138-33475e00-296d-11e9-8882-d61d013c2153.png)

**Comment by trudeau102000** [comment]
> Can you please download fresh 1.0.2 and delete forv2board.bin then rename generic.bin to forv2board.bin and then use flash.bat then chose option 2

 I went with option 3 then generic.bin that got me back up and running. right now it will work but i have to keep changing the gain save and reboot to get it to read again after a short time. if you want me to try that i will.

**Comment by trudeau102000** [comment]
i tried what you suggested on another esp but unfortunately I am right back where I started. I have it  kind of functioning if you don't mind the random loss of the reader function and total inability to trigger a relay. 
 great concept  though

**Comment by trudeau102000** [comment]
![giphy 7](https://user-images.githubusercontent.com/47269899/52481354-45e3b200-2b7c-11e9-9fca-a291ac4a4a7f.gif)

**Comment by nardev** [comment]
@trudeau102000 unfortunately any other reader but wiegand are quite demanding and with so much settings that it's sometimes hard to help.

please join http://esp-rfid.slack.com for chat help if you want.

Sometimes it's not a project issue, it's sometimes individual setup.

**Comment by trudeau102000** [comment]
> @trudeau102000 unfortunately any other reader but wiegand are quite demanding and with so much settings that it's sometimes hard to help.
> 
> please join http://esp-rfid.slack.com for chat help if you want.
> 
> Sometimes it's not a project issue, it's sometimes individual setup.

thanks. nardev, i have several esp's and  readers. so i have been able to duplicate the same issues over several setups. i also have a simple uno setup to verify the readers. they will work perfectly on the uno  but stop functioning once moved to any of the esp's at one point i had the reader working but it was always short term. sometimes changing the rfgain and restarting would bring function back. but again only short term. I have what i need now via a mega 2560 I really liked this project but the results are disappointing.

**Comment by msanchezt** [comment]
> @trudeau102000 unfortunately any other reader but wiegand are quite demanding and with so much settings that it's sometimes hard to help.
> 
> please join http://esp-rfid.slack.com for chat help if you want.
> 
> Sometimes it's not a project issue, it's sometimes individual setup.

How can I join this slack channel? Is asking for a specific domain which I do not own. Can't join with my own email address?

**Comment by nardev** [comment]
@msanchezt can you give me your email? You can send it to esprfid@gmail.com too.

**Comment by msanchezt** [comment]
Email sent, thanks.

*Marcel Sánchez Toledano*



Missatge de nardev <notifications@github.com> del dia dg., 3 de març 2019 a
les 20:22:
