### ISSUE TITLE
My mfrc522 does not seem to read the card

### ISSUE THREAD

**Issue by 1330154737** [omersiar/esp-rfid#24]
Hello, I am a novice learning esp8266, I follow the steps to connect the hardware, in the user interface in accordance with the format of the picture inside the card input UID, set the web page test button can be triggered, but the MFRC522 reader part did not respond
`[ INFO ] ESP RFID v0.3alpha
[ INFO ] Config file found
{
  "command": "configfile",
  "bssid": "74:7D:24:36:C3:C2",
  "ssid": "junhao",
  "wmode": "0",
  "pswd": "10086520",
  "sspin": "15",
  "rfidgain": "96",
  "rtype": "0",
  "rpin": "4",
  "rtime": "300",
  "ntpserver": "pool.ntp.org",
  "ntpinterval": "30",
  "timezone": "8",
  "hostnm": "admin",
  "adminpwd": "admin"
}
[ INFO ] Trying to setup RFID Hardware
[ INFO ] RFID SS_PIN: 15 and Gain Factor: 96
[ INFO ] MFRC522 Version: 0x92 = v2.0
[ INFO ] Trying to connect WiFi: junhao....
[ INFO ] Client IP address: 192.168.123.150
`

**Comment by omersiar** [comment]
Hello,

Did you try Dumpinfo example from MFRC522 library?

**Comment by 1330154737** [comment]
I tried burning mfrc522 example program, it did not work, but I found a problem that is even after burning mfrc522 test program can be seen in the router interface esp8266 connected to the wifi @omersiar

**Comment by omersiar** [comment]
[ INFO ] MFRC522 Version: 0x92 = v2.0

This means you succesfully connect the RFıD reader, it may be your rfid tags (piccs) are not for the reader. Try find mifare classic tag

**Comment by 1330154737** [comment]
Thank you for your reply, I use dumpinfo examples can read the card, but I follow the example connected rst pin

**Comment by 1330154737** [comment]
Thanks for your project, I modified Antenna Gain and now it's working

**Comment by omersiar** [comment]
Hello, great! Which gain value did you chose?

**Comment by 1330154737** [comment]
I chose 43😃
