### ISSUE TITLE
feature request: 1 or 2 Input eg PIR

### ISSUE THREAD

**Issue by hismastersvoice** [omersiar/esp-rfid#242]
It would be good to have 1 or 2 Inputs that can be Set via config site, and send an comand via MQTT.
I´m not sure if there are free Pins @ESP8266 but maybe there are. I´m using RC522.

So we are able to connect a button for a bell or/and an motion detector.

Thanks for your that great Project. I love it...

**Comment by omersiar** [comment]
Please see #220 Closing this issue and keeping it on #220
