### ISSUE TITLE
Recommend RFID reader?

### ISSUE THREAD

**Issue by msanchezt** [omersiar/esp-rfid#249]
Hi all,

Can someone recommend which is the best/good RFID reader for this Github project? I have been using it with the cheap RC522, but is giving me some troubles.
What is the RFID most tested? Or known to be the best for this specific project?

Thanks a lot.

**Comment by MrG1981** [comment]
Hi
I can't tell if this is the best reader
but it's working flawless for me for over 6 months now and it is not expensive

€ 3,37  6%OFF | Promotion Price Wiegand 26/34 Rfid Card Reader for Access Control System MF IC 13.56Mhz Card Reader Access Control Slave Reader
https://s.click.aliexpress.com/e/bpHRaDHX

Best Regards
Gregor

**Comment by omersiar** [comment]
I will prepare a recommendation section on README.

**Comment by Shanghaiman** [comment]
> Hi
> I can't tell if this is the best reader
> but it's working flawless for me for over 6 months now and it is not expensive
> 
> € 3,37 6%OFF | Promotion Price Wiegand 26/34 Rfid Card Reader for Access Control System MF IC 13.56Mhz Card Reader Access Control Slave Reader
> https://s.click.aliexpress.com/e/bpHRaDHX
> 
> Best Regards
> Gregor

I'm trying to use a wieagnd rfid IC 13.56 MHz with nodmcu amica board.
The readings of the card numbers are never same.
Can you share ur settings?
Tks
