### ISSUE TITLE
Cant Falsh Generic.Bin for the latest bulid 1.0.2

### ISSUE THREAD

**Issue by wessamvs** [omersiar/esp-rfid#252]
flash.bat keeps crashing when i select generic it worked with forV2Board.bin 
and the older version 8.1 is flashing generic.bin just fin 
ps: using nodemcu and rc522 
the pinout is correct i double  check

**Comment by omersiar** [comment]
Can you catch what is failing by starting flash.bat on command prompt?

**Comment by wessamvs** [comment]
![1](https://user-images.githubusercontent.com/38673559/54629378-20ea3500-4a80-11e9-8eb5-5c7ffc9913ce.png)
![2](https://user-images.githubusercontent.com/38673559/54629381-221b6200-4a80-11e9-9575-352a1a893371.png)
it crashed after the dots 
the nodemcu does not start or broadcast the WiFi after that
