### ISSUE TITLE
Don't flashing esp8266 (NodeMCU V3 Lolin)

### ISSUE THREAD

**Issue by 78Ronin78** [omersiar/esp-rfid#253]
Hello! I'am new user esp-rfid. How flashing NodeMCU V3 module ESP8266? My steps:
1. Connect ESP8266 to computer from USB-port (COM-port (COM5));
2. Run flash.bat
3. Choose Flash Generic Firmware and Enter
4. Chose COM-port - my port is COM5 and Enter
5. Nothing. In my console write "esptool v0.4.8 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>" after console is closing.
What i can do?

**Comment by 78Ronin78** [comment]
I have solution

**Comment by agoralive** [comment]
And what is this solution? 

Mine will not work after flashing :(
