### ISSUE TITLE
Mqtt control relay switch

### ISSUE THREAD

**Issue by zhangziran** [omersiar/esp-rfid#255]
Is there another way to implement Wiegand to read encrypted sectors?

**Comment by zhangziran** [comment]
.

**Comment by Netoperz** [comment]
wiegand, no. You need PN532 for example and some code to get the data, it's not a problem to do that , there are examples on the pn532 lib to red data, and on the gui you should add the place to input the password if you want to use own encrypted tada not the satandard keys.

As for wiegand, You need to buy reader that can work that way, for example ROGER has got this functions where you may preprogram the reader to read choosen sector with a default or predefined by admin key to decipher, and than it is throwing the output to the wiegand where you could catch the data using this device.

**Comment by zhangziran** [comment]
> wiegand, no. You need PN532 for example and some code to get the data, it's not a problem to do that , there are examples on the pn532 lib to red data, and on the gui you should add the place to input the password if you want to use own encrypted tada not the satandard keys.
> 
> As for wiegand, You need to buy reader that can work that way, for example ROGER has got this functions where you may preprogram the reader to read choosen sector with a default or predefined by admin key to decipher, and than it is throwing the output to the wiegand where you could catch the data using this device.

Hello, thank you very much for your reply and patient answers.
