### ISSUE TITLE
Problem mit Wlan/ Mqtt

### ISSUE THREAD

**Issue by DeUser** [omersiar/esp-rfid#256]
Hallo zusammen, ich schreibe einfach mal auf deutsch.
Ich habe da ein Problem und zwar scheint es bei mir zu MQTT Verbindungsabbrüchen in Verbindung mit einem Wlan ausfall zu kommen.
Sporadisch meldet sich mein ESP Rfid nichtmehr auf meiem MQTT im Iobroker an. Wenn ich den ESP Rfid dann aber neu starte funktioniert es sofort wieder.
Wie kann ich ihn dazu zwingen sich automatisch wieder bei dem MQTT Broker anzumelden ohne jedesmal selbst hand anzulegen?

**Comment by Netoperz** [comment]
english please

**Comment by omersiar** [comment]
Es tut mir leid für dieses Problem. Die MQTT-Funktion wird überarbeitet und korrigiert. Sie müssen möglicherweise eine Weile warten.

**Comment by omersiar** [comment]
#250

**Comment by omersiar** [comment]
Let's track this on #250. Closing for now.
