### ISSUE TITLE
Use wserver.js

### ISSUE THREAD

**Issue by 78Ronin78** [omersiar/esp-rfid#257]
Hello! I have one question, can I use a web server emulator, wserver. js as a server for writing data to the database SGLite for example? Or is it used only to configure the web interface and various tests? I do not ask to tell how to do it, I wonder if this is possible or not? Thank you in advance for the answer, I only study programming and many things are still not clear to me.

**Comment by omersiar** [comment]
It just simulates websocket messages that are normally coming from the esp8266. I believe there are no other use case available for it.

**Comment by 78Ronin78** [comment]
Last question on this issue - can i configure this emulator websocket for data transfer? I making procedure that saving data on SQLite data base. It remains only to transmit this data to the ESP via use mqtt-protocol.

**Comment by omersiar** [comment]
A nodejs application is totally capable of doing that.

**Comment by 78Ronin78** [comment]
Well, thank you so much! I have no more questions.
