### ISSUE TITLE
Running on different port

### ISSUE THREAD

**Issue by xc218m** [omersiar/esp-rfid#261]
To run it on different port, not 80 or if you want to have port forwarding using another port, you have to change line 4 in websrc\js\esprfid.js to:
var wsUri = "ws://" + window.location.hostname + ":" + window.location.port + "/ws";
and rebuild with builder.exe. 

Also it will be good to change the encoding of websrc\js\esprfid.js to UTF-8 in case someone (like me) wants to have text in another language.

**Comment by omersiar** [comment]
Thanks for the heads up. Will definitely include this in next release, also esp-rfid gets contributions around the world and sometimes (with Pull Requests) encoding of files end up being in different sets, I will try to fix this by automated checks.
