### ISSUE TITLE
Pinout for RDM6300 wrong

### ISSUE THREAD

**Issue by derLoosi** [omersiar/esp-rfid#262]
Heyho!

you made a mistake in the pin layout table:
when using a wemos d1 mini you need to connect the RDM6300 Tx pin to the WEMOS D1 mini Rx pin! D5 was not working for me, after connecting it to Rx it worked as i wanted :)

Greetings
Daniel

**Comment by Pako2** [comment]
Yes, that's a known thing. It is fixed in the [dev branch](https://github.com/esprfid/esp-rfid/tree/dev).

**Comment by omersiar** [comment]
Thanks for reporting, closing it for now.
