### ISSUE TITLE
Shorting gpio15 activates relay

### ISSUE THREAD

**Issue by zonk-242** [omersiar/esp-rfid#267]
**Expected Behavior**
   Nothing should happen when gpio15 (or any gpio) is shorted, pulled high or pulled low.

**Actual Behavior**
  Shorting gpio15 causes 'openLockButton.fell' to trigger when it shouldn't. As default 'openlockpin = 255' which means there is no open button configured. But shorting gpio15 activated the relay.
  
**Steps to Reproduce the Problem**
  Short gpio15 to ground.

**Possible Fix**
  Adding a check for 'openlockpin != 255' seems to remedy the problem.

###main.cpp###
	openLockButton.update();
	if (openlockpin !=255 && openLockButton.fell())
	{
#ifdef DEBUG
		Serial.println("Button has been pressed");
#endif

### ###

**Specifications**
Version: esp-rfid-1.0.2
Platform: Wemos D1

[ INFO ] Config file found
{
  "command": "configfile",
  "network": {
    "bssid": "",
    "ssid": "esp-rfid",
    "wmode": 1,
    "hide": 0,
    "pswd": "",
    "offtime": 0,
    "dhcp": 1,
    "ip": "",
    "subnet": "",
    "gateway": "",
    "dns": "",
    "apip": "192.168.4.1",
    "apsubnet": "255.255.255.0"
  },
  "hardware": {
    "readerType": 1,
    "wgd0pin": 4,
    "wgd1pin": 5,
    "sspin": 0,
    "rfidgain": 32,
    "wifipin": 255,
    "rtype": 1,
    "ltype": 0,
    "rpin": 13,
    "rtime": 400,
    "buttonpin": 255
  },
  "general": {
    "hostnm": "esp-rfid",
    "restart": 0,
    "pswd": "admin"
  },
  "mqtt": {
    "enabled": 0,
    "host": "",
    "port": 1883,
    "topic": "",
    "user": "",
    "pswd": ""
  },
  "ntp": {
    "server": "pool.ntp.org",
    "interval": 30,
    "timezone": 0
  }
}

**Comment by omersiar** [comment]
Thanks for reporting.
