### ISSUE TITLE
Use of Web Test Relay should be logged as an Event/Access.

### ISSUE THREAD

**Issue by zonk-242** [omersiar/esp-rfid#268]
**Expected Behavior**
  Activating the relay via the web 'Test' button should have an Event/Access log generated.

**Actual Behavior**
  Using the 'Test' button on the 'Hardware Setting' web page activated the physical Relay but does not log anything.

**Steps to Reproduce the Problem**

**Possible Fix**

**Specifications**
Version: esp-rfid-1.0.2
Platform: Wemos D1

**Comment by omersiar** [comment]
Thanks for reporting.
