### ISSUE TITLE
http Request

### ISSUE THREAD

**Issue by mumpitz78** [omersiar/esp-rfid#270]
Good day
I want to use this super cool firmware to read an RFID reader with a NodeMCU. The goal is to control a Nuki door lock. Is it possible to trigger a http request with your firmware, if an authorized person has authorized himself?
The advantage would be that I would not have to go through an MQTT server.

Thank you for your answer and greetings from Switzerland

**Comment by zonk-242** [comment]
From what I see in the code this is only possible via MQTT.

**Comment by laserir** [comment]
This feature would be super helpful!! Please think about adding it!!

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.
