### ISSUE TITLE
allow & reject times in HTTP

### ISSUE THREAD

**Issue by impactphil** [omersiar/esp-rfid#271]
Hi, great work on your board, I have just received mine and am starting to set it up.
Can you could add some extra inputs in the users section on the web browser page to restrict times and/or days that the unit could stop cards from working.
I am planning on using mine to control a boundary gate and would like to give some people access only during certain times of the day and days of the week.
For example:
set certain day or days that contractors could have access
parcel deliveries between certain hours
utility companies access to read meters
rubbish collectors only twice a week

Thanks
Philip

**Comment by omersiar** [comment]
Yes, this is considered as future development. I'm closing this for now, please feel free to reopen if you want additional help.
