### ISSUE TITLE
Invalid head of packet (0xE0)

### ISSUE THREAD

**Issue by ccfiel** [omersiar/esp-rfid#272]
Configuring flash size...
A fatal error occurred: Invalid head of packet (0xE0)

Any idea why I have this error when I execute this step `platformio run -e generic -t upload` ?

Specs
1. Wemos D1 mini
2. Ubuntu 18.04
3. PlatformIO, version 3.6.7

**Comment by zonk-242** [comment]
Looks like platformIO cannot find your ESP device.
Did you check to see that the Wemos D1 is connected to Ubuntu? Which Com port is it using?

Reset or power cycle the Wemos D1 just before you upload from platformIO. I've seen my ESP8266 fail to upload if it's been on for a while.

Make sure that you don't have a serial monitor open in the background.

**Comment by ccfiel** [comment]
@zonk-242 I think its not the Wemos because when I use directly esptool.py it works perfectly.
```
esptool.py --port /dev/ttyUSB0 write_flash -fs 4MB -fm dout 0x0 firmware.bin
```

**Comment by fwestenberg** [comment]
I had the same issue when flashing my Nodemcu. Solved it by changing the upload_speed parameter in platformio.ini to 115200.

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.

**Comment by jamesawebb** [comment]
+1 on changing baud from default of 921600 to 115200.
