### ISSUE TITLE
is there a way to reset all settings without flashing again

### ISSUE THREAD

**Issue by vetruk** [omersiar/esp-rfid#276]

**Comment by omersiar** [comment]
If you do not want retain user data as well, you can use Factory Reset.

**Comment by omersiar** [comment]
Or you can backup user data and do the factory reset then restore them.

**Comment by vetruk** [comment]
The problem that ocurs often is that when wifi password is set and if is
shorter than 8 symbols device become inresponsive. Sometimes even with more
than 8 symbols. Is there a way to soft  reset settings and data anyway.
What does mean Factory reset.

На пн, 17 юни 2019 г., 15:00 Ömer Şiar Baysal <notifications@github.com>
написа:

**Comment by vetruk** [comment]
How about some dedicated button support for soft reset on WiFi settings.
Or all settings. On startup function to reinitialize settings file. Like if its pressed on startup to start to wipe the flash file system and making new files.

**Comment by omersiar** [comment]
A typical WPA passphrase should be consist from at least 8 characters. I think code doing a check for that but I'm not sure at the moment. We have had the push button reset feature in the past, to reduce number of used GPIO I removed the feature. With the factory reset, I mean a menu item that is listed on the left menu, you need functioning WebUI to use it though.

**Comment by vetruk** [comment]
I check the code and no length check so far. When wifi password is less than
8 characters the esp lock it self and constantly trying to wake up wireless
and freezes like that and only solution that i found so far is to program
with empty bin and so on.. If you dont have problem to look at that code
that you have in the past it will be nice!

На пн, 17 юни 2019 г., 16:43 Ömer Şiar Baysal <notifications@github.com>
написа:

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.
