### ISSUE TITLE
Change LED-color

### ISSUE THREAD

**Issue by bib2** [omersiar/esp-rfid#284]
Hi,
with 1.0.2 my LED color in standby is green and when i move a rfid-tag to the reader, it flashes blue.

With 1.3.1 my led color in standby is blue and changes to green when i move a rfid-tag near my reader.

Is there a way to set the color for standby and reading by myself?

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.

**Comment by bib2** [comment]
Why do you close this? Is there an answer somewhere or have you changed something in the code?

**Comment by omersiar** [comment]
What you can do is checking for the output GPIO for your led and find if there any changes were made, then you may edit source code according to your needs. I think there are tools available for git to inspect the difference between versions.

**Comment by omersiar** [comment]
Let me know if this case should be remained opened. Kind regards.

**Comment by bib2** [comment]
Maybe you can add this to the next version, so that users can change the led color inside the configuration webif?

Sadly i´m no programmer and i don´t know how to change something in github and build my own source code...
