### ISSUE TITLE
problem with original pcb 

### ISSUE THREAD

**Issue by zefirpsaryanov** [omersiar/esp-rfid#287]
hello, very good project
I already bought a 1 pcb
together with my friends we discussed it and we so excited :) 

1st suggestion - device need some brute force attack defense 
(5 wrong cards -  reboot  or GPIO disable for 1 min or something )

2nd suggestion - web unlock :) (but not necessary - test relay works very good :) )

1st problem - after restart - there is no 12V on Relay Type - Active Low state
it did not work with forV2Board.bin 1.3.1 and factory 1.0.2
BUT it works with generic.bin as i expect 👍 (1.3.1)

2nd problem - logging - enable( 50lines ) / disable

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.
