### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by zefirpsaryanov** [omersiar/esp-rfid#288]
hi again .. :)
i need some help about adding a button for opening the door from inside 
i spent 2 h of reading documentation again and again ... and i can`t understand how to add it 
is it possible atm

**Comment by teriall** [comment]
1.3.3 release has button option in Menu > Settings > Hardware settings

**Comment by zefirpsaryanov** [comment]
i have downloaded 1.3.3 BUT in esp-rfid-1.3.3.zip all versions are 1.3.1 (generic , debug and forV2Board.bin)

**Comment by teriall** [comment]
you need to erase whole flash first, then flash the firmware

**Comment by zefirpsaryanov** [comment]
pcb is death .. so i 1st have to revive it .. i have to find where is my ttl usb :)

**Comment by teriall** [comment]
There is nothing to die except probably the EPS module. It's cost $2 and you can get in local electronic shops.

**Comment by zefirpsaryanov** [comment]
revived .. so i really cannot understood how to add physically button for opening the door 
anybody know or i'll burn it again :)

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.
