### ISSUE TITLE
new feature 

### ISSUE THREAD

**Issue by zefirpsaryanov** [omersiar/esp-rfid#289]
Scheduled auto lock 
default OFF 
ON at Scheduled time

**Comment by arretx** [comment]
You can already do this by integrating your lock into Home Assistant and using continuous mode.  Your choice of on or off is done by how you wire up the relay (Normally open, or normally closed.)  Then, use MQTT to trigger the door.

**Comment by omersiar** [comment]
I'm closing this for now, please feel free to reopen if you want additional help.
