### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by laserir** [omersiar/esp-rfid#290]
Is it possible to SET (e.g. add/delete a user) or GET (e.g. user list) settings by sending a POST/GET-request to the device webserver? Would be perfect for hotel access systems...

**Comment by arretx** [comment]
Using NodeRED and MySQL coupled with marelab's NodeRED flow for the RFID door, you can do this.

**Comment by laserir** [comment]
Thanks for the answer, but could you go a little further into detail?
