### ISSUE TITLE
ESP Async WebServer - FAILED

### ISSUE THREAD

**Issue by kodibrain** [omersiar/esp-rfid#291]
` ^
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\AsyncEventSource.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\AsyncWebSocket.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\SPIFFSEditor.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\WebAuthentication.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\WebHandlers.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\WebRequest.cpp.o
Compiling .pio\build\generic\liba86\ESP Async WebServer_ID306\WebResponses.cpp.o
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(tm*)':
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp:67:64: error: 'strftime' was not declared in this scope
   strftime (result,30,"%a, %d %b %Y %H:%M:%S %Z", last_modified);
                                                                ^
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(time_t)':
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp:73:60: error: 'gmtime' was not declared in this scope
   return setLastModified((struct tm *)gmtime(&last_modified));
                                                            ^
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified()':
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp:78:25: error: 'time' was not declared in this scope
   if(time(&last_modified) == 0) //time is not yet set
                         ^
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(time_t)':
.pio\libdeps\generic\ESP Async WebServer_ID306\src\WebHandlers.cpp:74:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
*** [.pio\build\generic\liba86\ESP Async WebServer_ID306\WebHandlers.cpp.o] Error 1
=============================================================================================== [ERROR] Took 5.64 seconds ===============================================================================================

======================================================================================================= [SUMMARY] ======================================================================================================= 
Environment generic     [FAILED]
Environment relayboard  [IGNORED]
Environment debug       [IGNORED]`

**Comment by zefirpsaryanov** [comment]
same here :)

**Comment by kodibrain** [comment]
Here is the answer :) 

https://github.com/esprfid/esp-rfid/issues/201#issuecomment-443492816
