### ISSUE TITLE
esp-rfid connects only to a router with correct mac adress

### ISSUE THREAD

**Issue by bib2** [omersiar/esp-rfid#295]
Hi, i have some problems:

My esp-rfid connects only to a explicit router with its unique mac adress. Now i have changed the router, everything is working, only the esp rfid doesn´t connect, becuase the new router has a new mac adress.

Can you remove the mac adress from the wlan settings? Every other wlan device connects to a wifi on every router i have in the house, only the esp-rfid connects to the one it was connected with webinterface. So when i move the esp-rfid in my house to a place where another wifi-router is, i don´t have access any more.

How can i connect to the esp-rfid, when the old wifi-router isn´t available any more?

**Comment by arretx** [comment]
Switch the board back to Access Point mode and connect to it directly, then reconfigure the WIFI to connect back to your WIFI network.

**Comment by bib2** [comment]
I did it another way: I sold the old router to a friend, so i called him to bring it back to me and then i was able to connect to the esp again. Then i simply removed the mac adress from the field and it now works with every router.

Without the old router i was not able to connect to the esp over wifi to switch it to ap mode.

**Comment by omersiar** [comment]
Ok this is a bug, thanks for reporting it.

**Comment by frenchie71** [comment]
@omersiar , could you check Pull request #307 again please - I have added a second commit which would fix this issue and issue #251 - thanks ;-)

**Comment by vrelk** [comment]
Using the release as of a few days ago, I did have an issue where removing the BSSID caused it to go into AP mode without showing it as such in the web admin. I have since gotten it to act as a client without specifying a BSSID by connecting with a BSSID, then removing it.


@omersiar This did lead to the idea of a nice feature. If it is unable to connect to the specified AP (ex, it's missing), switch to AP mode.

**Comment by matjack1** [comment]
This should be fixed here: https://github.com/esprfid/esp-rfid/pull/307 in the dev branch for now.
