### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by walliek** [omersiar/esp-rfid#297]
hi there,

i have a question, i cant get it working.
i flash the software on the device. (esp2866)
connect to the wifi works, web page works perfectly.
i fill in the wifi settings, hardware setting, general setting. i press safe and reboot.
connect back to my wifi, i can find the device. go to the device ip. fill in password. then i come on the status page but its blance, user page doenst work either and all setting are back the same.  what am i doing rong?
<img width="1159" alt="Schermafbeelding 2019-08-05 om 13 32 34" src="https://user-images.githubusercontent.com/29761017/62462032-a566f700-b786-11e9-9a92-3e6a87b16f6f.png">
<img width="1147" alt="Schermafbeelding 2019-08-05 om 13 32 41" src="https://user-images.githubusercontent.com/29761017/62462037-a861e780-b786-11e9-8076-f59db9e5cb10.png">
<img width="1114" alt="Schermafbeelding 2019-08-05 om 13 39 47" src="https://user-images.githubusercontent.com/29761017/62462043-aac44180-b786-11e9-863a-fb3477a6286f.png">

**Comment by Ralph74** [comment]
Same problem here. Can flash the esp8266 fine. Device will generate the AP and I can login with the default password however I cannot save ANY changes. It says it is 'Please wait while your ESP restarts', progress bar gets to 100%, says completed. AP stays active. If I reboot ESP, AP still active and any changes have been reverted to default. I tried v 0.9.3, 0.9.4, 1.3.3 Firefox, Chrome, IE. All with the same results. Surely its not the way I'm flashing it (using  NODEMCU FIRMWARE PROGRAMMER)

**Comment by walliek** [comment]
I jused also every version, started from 0,7

Tryed also different board, wemos d1 mini 3.1 same issue. Start to think its the rfid reader. Orderd some new ones now.

**Comment by beroliv** [comment]
i have the same issue:
My work around as follwow:
 after reboot login
use a menu to make the setting,
 save the new setting and restart..
then next setting you want change. not nice but works so far.

**Comment by Ralph74** [comment]
OK. Now trying D1 Mini. I have the console working now with some useful info:
[ WARN ] Failed to open config file
this will be why no settings are saving. Now to work out why?

**Comment by walliek** [comment]
found the solution, dont use chrome, safari, firefox, vivaldi. tryed them al. college of mine used microsoft edge and it worked for him.(also use a windows pc or i used paralles on mac) so i reflashed my esp directly, open microsoft edge, setup  everything. en voila it worked... let me know if ut work for u guys

**Comment by Ralph74** [comment]
MS Edge did not work for me. @walliek can you please tell exactly how you flashed your device?

**Comment by arretx** [comment]
Flashed my device using a Mac with NodeMCU PyFlasher version 4.0.  Flashed the generic.bin from the 1.3.3 patch release.  It's hit or miss it it seems.  Once it takes, it works, but there are other problems with the entire system that I'm trying to figure out.

**Comment by walliek** [comment]
@Ralph74 i just use the flash file. What is in the map.

I also order a new RC522. First had 1 from aliexpress. Now i order the one That drzzs linked in is command on youtube. Its working perfect now for me

**Comment by Ralph74** [comment]
What the heck is going on now!
![image](https://user-images.githubusercontent.com/11015914/63422859-82a73480-c44e-11e9-9360-bd0acef39877.png)
Where did generic.bin go?

**Comment by walliek** [comment]
You are on the rong page, https://github.com/esprfid/esp-rfid/releases/tag/1.0.2

**Comment by omersiar** [comment]
I'm closing this, please feel free to reopen if you want additional help.
