### ISSUE TITLE
after Wlan lost device not reconnect

### ISSUE THREAD

**Issue by beroliv** [omersiar/esp-rfid#298]
after Power-cycle my Wifi the rf id reader do not reconnect anymore. It needs to power-cycle also each time the rfid reader lost WIFI.

**Comment by alegiovannelli** [comment]
I found out I had the same problem yesterday. After the wifi network is restarted the card does not connect again and does not even restart in configuration mode, the LED flashes. Practically the only way to make it work is to restart it manually.

**Comment by omersiar** [comment]
Wi-Fi behavior will be improved as suggested. Thanks for reporting, you are heard, closing it for now.
