### ISSUE TITLE
Card scanned reports new ID, can't match user.

### ISSUE THREAD

**Issue by arretx** [omersiar/esp-rfid#301]
I didn't expect this one.

Yesterday I programmed 2 cards and one keyfob in the user list.  Yesterday each card would activate the lock.

Today, when I scan the same cards and keyfob, the ID seems to have changed and the card(s) / key(s) are not recognized by the system, and as a result, the lock doesn't activate.

Is this a bug?

**Comment by omersiar** [comment]
Hello,

Thanks for using esp-rfid software. Some of the keyfobs may choose to implement what we call RID feature, in this case each time the keyfob is energized it simply generates a random UID. Currently esp-rfid can not work with these kind of RFID chips (tags, keyfobs, etc).

Kind regards.

**Comment by arretx** [comment]
I don't believe that is the case for these cards.  So far, any card that has had a different number appear when scanning has only alternated between two numbers.  Are you suggesting that when the antenna is charged, the chip on the card or keyfob responds with either a single code, or potentially a random code from either a list of codes embedded on the chip, or a randomly generated code on the fly?

**Comment by arretx** [comment]
What is the solution for this?  Every time I scan a card it presents a new user ID.  Naturally this won't work.  Is it the Weigand reader, or is it the card?  If it's the reader, which reader do I need?  If it's the card, which cards should I use.  I've been through 2 readers and 2 different sets of cards now and I have the same issue.
