### ISSUE TITLE
Allow raw value in restart combobox

### ISSUE THREAD

**Issue by GeertvanHorrik** [omersiar/esp-rfid#305]
Somehow my setup seems to hang itself after some hours, probably related to network reconnect issues of some kind. Then I checked the restart period (lowest is 24h). But it's stored as seconds, so would be really nice if this could be:

1. Set directly instead of the combobox
2. Customization of the json would be allowed

**Comment by GeertvanHorrik** [comment]
btw probably related to https://github.com/esprfid/esp-rfid/issues/298

**Comment by omersiar** [comment]
Yeah, why not.

**Comment by matjack1** [comment]
I've added support for this here: https://github.com/esprfid/esp-rfid/pull/552

**Comment by matjack1** [comment]
It's now merged on `dev` :)

I'm closing this, if anyone has problems though, please reopen!
