### ISSUE TITLE
Multiple logins to web interface causes crash/unresponsiveness

### ISSUE THREAD

**Issue by peteshoard** [omersiar/esp-rfid#311]
Opening the web console from 2 or more separate locations causes the esp/application to freeze and become unresponsive.

Suggest a timeout/disconnect from a remote session / single session only call in web interface code.

**Comment by matjack1** [comment]
hey @peteshoard I know this is pretty old, but I think this is fixed with the code that you can find here: https://github.com/esprfid/esp-rfid/pull/577

I'm closing this for now, but if necessary please reopen!
