### ISSUE TITLE
Time zone deleted after reboot

### ISSUE THREAD

**Issue by satreddys** [omersiar/esp-rfid#316]
I've synced the browser time and set the time zone. But after restarting the device, the time zone is not saved and showing back to 1970-01-01 date. Did I miss anything? or is this an issue?

**Comment by omersiar** [comment]
The time gets reset on each reboot so you need to manually sync browser time to your device.

**Comment by omersiar** [comment]
Closing it for now. Feel free to re-open if you need further help with esp-rfid software.
