### ISSUE TITLE
Auto Disable Wifi not working in AP mode

### ISSUE THREAD

**Issue by adcomrod** [omersiar/esp-rfid#319]
I looked first on current open and closed issues but nothing like this found.
I could not make the wifi disabled (using the setting "Auto Disable Wifi") if the node is in access point mode.
When set as client is working ok, but as AP the wifi keeps always on, even though the "Auto Disable Wifi" is set to any other than "always on".
I think is useful to be able to disable wifi in standalone mode to add some extra security to the node.
Adrian

**Comment by omersiar** [comment]
Thanks for reporting it.

**Comment by matjack1** [comment]
Thank you for this report, it makes total sense!

I've fixed it in here: https://github.com/esprfid/esp-rfid/pull/497

I'm closing this for now, but please reopen if necessary.
