### ISSUE TITLE
Reboot with http-request

### ISSUE THREAD

**Issue by WAVez86** [omersiar/esp-rfid#320]
Hi everyone, real nice project!
I have the problem that the mqtt broker is losing the connection every one till two days.
At the moment my broker sends me a mail and i restart the device with the web-ui per hand.
So I'd like to restart the device automaticly if the mqtt broker is losing the connection. Is there a chance to do this via http-request (e.g. http://IP/api/restart)?
This would help me so much.
Thanks in advance.

**Comment by adcrafter27** [comment]
I am also looking for that

**Comment by matjack1** [comment]
@WAVez86 @adcrafter27 there's already an issue here: https://github.com/esprfid/esp-rfid/issues/530 to restart the device via MQTT (the currently supported API).

But is your problem occurring with the `dev` branch?

**Comment by DivanX10** [comment]
> Hi everyone, real nice project! I have the problem that the mqtt broker is losing the connection every one till two days. At the moment my broker sends me a mail and i restart the device with the web-ui per hand. So I'd like to restart the device automaticly if the mqtt broker is losing the connection. Is there a chance to do this via http-request (e.g. http://IP/api/restart)? This would help me so much. Thanks in advance.

Now it is implemented, you can read the details [here](https://github.com/esprfid/esp-rfid/issues/530#issuecomment-1304606607)

**Comment by DivanX10** [comment]
A working reboot command via the MQTT service for this [firmware](https://drive.google.com/drive/folders/15WgpG_04JhWDdBxhBjB9pIWSCzyGV4ll)

```
service: mqtt.publish
data:
  topic: esprfid/cmd
  payload: "{cmd:'reboot',doorip:'192.168.1.48'}"
```

**Comment by matjack1** [comment]
I'm going to close this now then
