### ISSUE TITLE
Logging into web interface triggers relay

### ISSUE THREAD

**Issue by arretx** [omersiar/esp-rfid#323]
In HA, I have a sensor that monitors the "open door" feature on the official relay board using the unpowered side of the relay as a switch to close the loop on the door sensor pins.

So, when the lock is active, Home Assistant knows it active:

```
- platform: mqtt
  name: "Southwest Sanctuary Door"
  state_topic: "rfid/send"
  value_template: >-
    {% if value_json.desc == "Door Open" %}
      Unlocked
    {% else %}
      Locked
    {% endif %}
  json_attributes_topic: "rfid/send"
```
Granted, it only knows if it receives a message.

When I login to the web interface and enter my password, the relay toggles quickly, and if the door is locked, it releases it and then activates the lock again.  If the door isn't locked, it activates the lock and de-activates it.

Whether or not the door is secure in either scenario is a function of how well the door's auto close mechanism is working and how well the plate rests against the magnet.  Unfortunately, not every door is square and plumb, so I have to rely on inertia (door closing) to make contact with a live magnet in order to ensure it's locked.  I can't just release and re-activate and expect it to be locked.

So, at this point, when I login, the relay is tripped.  Is there a way to stop this behavior?

**Comment by matjack1** [comment]
I think this is now fixed. I'm going to close, but feel free to reopen if there's still a problem.

I've recently tested the HA integration (in the `dev` branch) and it worked fine.
