### ISSUE TITLE
Compiling Error 

### ISSUE THREAD

**Issue by sanjulanipun** [omersiar/esp-rfid#327]
anyone know how to fix it

![image](https://user-images.githubusercontent.com/32708235/66542413-1f817680-eb50-11e9-93a0-7118fa8a1ebc.png)
![image](https://user-images.githubusercontent.com/32708235/66542500-5c4d6d80-eb50-11e9-9c16-b699f9879fe0.png)

![image](https://user-images.githubusercontent.com/32708235/66542423-2b6d3880-eb50-11e9-95c0-93eee41aef79.png)

**Comment by cipiasentini** [comment]
I've got some compiling errors too
<img width="1207" alt="io" src="https://user-images.githubusercontent.com/28297294/67160184-75120c00-f324-11e9-9c20-bca56d0f0f8e.png">

**Comment by bigshit11elf** [comment]
Had the same errors... created a virtual machine, installed ubuntu, installed "Atom", installed "Python2", installed "PlatformIO" as a package, got it to compile without errors.

Don't know whether this fixes my issues with pre-compiled V1.3.3 (access log empty, wrong version number).

**Comment by alfredtorch** [comment]
The same error here. I solved it by adding this to platformio.ini
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
and clean. Still troubleshooting upload (A fatal error occurred: Invalid head of packet (0x80))....

**Comment by cyberhasse** [comment]
Try changing upload speed to 115200

**Comment by matjack1** [comment]
I'm closing this as I think it's obsolete, but if you still need help let me know!
