### ISSUE TITLE
When editing an "Admin" card, the webinterface shows "Disabled" in the dialog.

### ISSUE THREAD

**Issue by saschaludwig** [omersiar/esp-rfid#33]
Steps to reproduce:

1. Add a card with access type "Admin"
2. reload the browser (User Table display of newly added cards is broken as well)
3. edit the "Admin" card -> Modal Dialog shows "Disabled" in field Access Type.

**Comment by omersiar** [comment]
Thank you for the heads up and generous donation. User types will be completely refactored to adapt more use case scenarious.
