### ISSUE TITLE
Auto restart doesn't work

### ISSUE THREAD

**Issue by bad-gargoyle** [omersiar/esp-rfid#331]
I have problem that my Wemos D1 Pro wont autorestart when I set auto restart option on.

PS Should RST pin (how) be wired?

**Comment by beroliv** [comment]
same here..

**Comment by bad-gargoyle** [comment]
May we consider the problem confirmed?

**Comment by runt** [comment]
I am not really IN, only quickly seeing source main.cpp :

uptime is in seconds ( main.cpp, line 236 = uptime = NTP.getUptimeSec(); )
autoRestartIntervalSeconds is in seconds too

but on line 350 is autoRestartIntervalSeconds multiplied by 1000:

if (autoRestartIntervalSeconds > 0 && uptime > autoRestartIntervalSeconds * 1000)
	{
		writeEvent("INFO", "sys", "System is going to reboot", "");
#ifdef DEBUG
		Serial.println(F("[ WARN ] Auto restarting..."));
#endif
		shouldReboot = true;
	}

if I set in config.json restart=1, then I get autorestart after about 16mins ( 1000s = 16.6667min )

problem confirmed, possibly multiplying in "if" is wrong
sorry for my english

**Comment by bad-gargoyle** [comment]
How could I edit/correct (not via GUI) value of autoRestartIntervalSeconds parameter? Is it necessarily to compile new version from source?

PS Could someone pass me link for "know how" for such procedure?

**Comment by windy54** [comment]
Install vscode and platform io extension. Download code from GitHub and open in vscode, click on the  “tick” icon to build.
I posted this and then noticed the instructions on the main page and I have fixed this in our hackspace version by deleting the 1000

**Comment by matjack1** [comment]
Fixed here: https://github.com/esprfid/esp-rfid/pull/552

Can anyone please confirm?

**Comment by matjack1** [comment]
I'm closing this, in case anyone has problems, please reopen!

**Comment by windy54** [comment]
I have just tried it and it did not re-start. It was supposed to re-set
every 24 hours but has been up for over a day.

I will check the code later on and confirm i have got the latest
development build.

Steve

**Comment by windy54** [comment]
Ignore my email, I have jus5 checked the code and have not got the latest, having reviewed the code it will work restart time is in seconds and that is wha5 uptime returns.

Apologies for confusion

Cheers
Steve Gale

**Comment by matjack1** [comment]
Thank you for checking, very appreciated!
