### ISSUE TITLE
Connectivity loss after router restart

### ISSUE THREAD

**Issue by s0170071** [omersiar/esp-rfid#334]
if I restart my router, esp-rfid does not re-connect to the network once it comes back.
It takes about 4 minutes for the network to come back if I restart my router. 

Is this a bug or a feature ?

**Comment by omersiar** [comment]
This is not a bug, simply there is no logic programmed for reconnecting.

**Comment by omersiar** [comment]
You can schedule an auto restart.

**Comment by bad-gargoyle** [comment]
Restart in some cases (on Wemos) doesn't work. :-(

**Comment by s0170071** [comment]
Never mind, I migrated to ESPEasy.  This also soved the poor connectivity / RSSI issues.
