### ISSUE TITLE
1.3.5 test

### ISSUE THREAD

**Issue by beroliv** [omersiar/esp-rfid#337]
-Auto-restart is working with the 24h setting
- after loosing the network the device is going back to make his own network (AP Mode)
- after klick the Logs (access and event)the Page is not working properly anymore, first relod the page and login again solve the Problem. I have it on my desk just for testing.
The webui freezes with "**Please wait while fetching data..**."
I recover the user data. I need to do the recover twice till it works and recover the data with each file. (User and System)

**Comment by beroliv** [comment]
relay Pin did not work in 1.3.5! After flashing back to 1.3.3 Relay is back working

**Comment by bad-gargoyle** [comment]
I dont need relay PIN usage. More important is ability to auto restart after 24h. - So, is it safe for me to use 1.3.5 version?

MQTT is working? Will I lose config and user data?

**Comment by bad-gargoyle** [comment]
Sorry, I had to try. ;-) Not only after loosing the network is going to AP mode. After simple restart too. I'm back at 1.3.3 and waiting for final or at least the beta version of 1.3.5.

**Comment by beroliv** [comment]
i change my wiring so it works with out wifi. 1.3.5 i do no recomment for using

**Comment by beroliv** [comment]
what you can try to reenable Wifi is: Set access Typ to admin and switch Wifi off after 10 Minutes

**Comment by bad-gargoyle** [comment]
I must do some test before. I'm curious how will MQTT connection will react (will it be still working, how big lags there will be).

**Comment by beroliv** [comment]
i try alredy, you have to read the key twice. First read wakup wifi, second read opens the door

**Comment by bad-gargoyle** [comment]
Thats not good for me. For now, version 1.3.3 hangs (more or less) once a week. The other thing is that it will not auto reconnect to MQTT when I'm restarting MQTT server/broker. That are main disabilities for me. I have to live withe them for now.

I could always add relay that will reboot my device after each success RFID access. ;-)

**Comment by beroliv** [comment]
yes it was my hassel too. i use it now autom without any wifi and mqtt. opens the door very quick.
Another intressting Projekt but not finish yet.
https://github.com/mdrobisch/roseguarden
https://gitlab.com/roseguarden/roseguarden

i think need a lot of time to finish

**Comment by bad-gargoyle** [comment]
In my case all logic and action are implemented and made on central linux server, inside OpenHab. It's better solution, as I could flexibly change RFID scan action for desired OpenHab action depend my actual needs. For examlpe, not only open gate/wicket when scanned, but aditionaly turn on light on front of house before that, if it's dark outside, and aditionally send frame captured from CCTV as JPG to my telegram acount.

I think I just have to wait for new version.

**Comment by beroliv** [comment]
hm but you can try. my beeper is on the relay pin - he made a short beep. Its to short to open the lock but maybe long enough for your needs.

**Comment by frenchie71** [comment]
Hi @omersiar , Checking my last pull request I have realized that I had not compiled the websources in the commit. That might actually be the issue as pull request #318 made changes to esprfid.htm and esprfid.js - can you please try again with freshly compiled websources (i.e. run gulp.js and then commit) ? basically the webinterface changed due to the fact that you could now select multiple relays.

**Comment by matjack1** [comment]
I'm closing this as it looks obsolete now. But please reopen if you need anything else here.
