### ISSUE TITLE
Sending periodical when RFID is read

### ISSUE THREAD

**Issue by Shogun1978** [omersiar/esp-rfid#34]
Is it possible to continue sending MQTT-Messages while a RDIF tag is placed on the reader? Or send a message when it is placed on the reader and another (different) message when it's removed? Function should be similar to a hotel card plugged in slot near the door.
The usage will be a smart home "switch" to send a MQTT message, when e.g. a NFC tag of a phone is placed on the reader to signal night mode.

**Comment by omersiar** [comment]
It is possible indeed. See https://github.com/miguelbalboa/rfid/issues/352 for detecting removed RFID tag.

**Comment by Shogun1978** [comment]
Thank you, I will take a look at this solution.
