### ISSUE TITLE
allow a tag in a time period

### ISSUE THREAD

**Issue by xmow49** [omersiar/esp-rfid#342]
Hi, 
Is it possible to allow a tag in a time period and each tag has his time period?

thx

**Comment by nardev** [comment]
Not yet.

**Comment by xmow49** [comment]
ok

**Comment by evazzoler** [comment]
I follow.
(I need it)

**Comment by omersiar** [comment]
This is already in our to-do list. Closing it for now. Feel free to re-open if you need further help with esp-rfid software.
