### ISSUE TITLE
Module relay 5v not working

### ISSUE THREAD

**Issue by adi160885** [omersiar/esp-rfid#344]
sir, how to use the 5v relay module, because I use NodeMcu v3 there is no 5v output power only 3.3v, so the 5v relay module doesn't work, I've tried using (step up module) from 3.3v output but the 5v relay module doesn't work, please the solution, thank you.

**Comment by kacitran** [comment]
link photo
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTyPjw2TzDluevxNvkuyQRziaBKT3yNrfv4K9wsrCu9H8dS4OKH

https://i.stack.imgur.com/wvSuY.png

**Comment by adi160885** [comment]
Thanks sir

**Comment by marceltech** [comment]
> link photo
> https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTyPjw2TzDluevxNvkuyQRziaBKT3yNrfv4K9wsrCu9H8dS4OKH
> 
> https://i.stack.imgur.com/wvSuY.png

Hello,

How to use a nodemcu + 3v relay?

**Comment by kacitran** [comment]
> > link photo
> > https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTyPjw2TzDluevxNvkuyQRziaBKT3yNrfv4K9wsrCu9H8dS4OKH
> > https://i.stack.imgur.com/wvSuY.png
> 
> Hello,
> 
> How to use a nodemcu + 3v relay?

I do not understand your question?
It has a 3v relay, and you want it to be operated with pin nodemcu?
You need an electronic circuit to activate the relay.
Google search you will find many options.
![Fritzing_bb-768x604](https://user-images.githubusercontent.com/58903301/72103825-53745f80-332a-11ea-9a81-fef2a7bc1408.png)
https://www.geekering.com/?p=187

**Comment by omersiar** [comment]
Closing it for now. Feel free to re-open if you need further help with esp-rfid software.
