### ISSUE TITLE
esp-RFID - Roger

### ISSUE THREAD

**Issue by kambiumdt** [omersiar/esp-rfid#349]
Hello.

I wanna use w rfid reader of roger: prt12em-bk-g

How program them, to work with esprfid?
![obraz](https://user-images.githubusercontent.com/59489029/71751383-af973980-2e7b-11ea-848a-761f7c04f953.png)

i try with wiegand 26, and any pf the X
but nothing have to work.
I connect d0 and D1 just to nodemcu.

it should be connect via volatage converter ??

Any help?

**Comment by nardev** [comment]
In most cases, the esp8266 can tolerate 5V wiegand signal.

**Comment by marceltech** [comment]
> In most cases, the esp8266 can tolerate 5V wiegand signal.

Does nodemcu can provide the 3v or 5v inside of GPIO?

**Comment by nardev** [comment]
It's 3v3 logic.
