### ISSUE TITLE
Not able to build "dev" branch with new "Platform" settings in platformio.ini

### ISSUE THREAD

**Issue by christofkac** [omersiar/esp-rfid#354]
Hi,
I just cloned the "dev" branch to build eps-rfid with all the nice features.
Using the commandline "platformio run" on windows as decribed in the manual, I get many build errors.
I captured the output here: https://pastebin.com/Vjv17b9F

As I was successfully able to build stable I checked the differences and found out, that changing the platform in platformio.ini back to the version from stable enables me to build.

So my configuration of [common] is now the following:
`[common]
;platform = espressif8266@2.0.4
;platform = espressif8266@2.2.3
platform = https://github.com/platformio/platform-espressif8266.git `

which builds successfully.
Neither of the above lines (2.0.4 / 2.2.3) is buildable.

I just checked the platformio github page https://github.com/platformio/platform-espressif8266/releases and have seen, that 2.3.2 is the latest.
After checking 
platform = espressif8266@2.3.2
I can confirm that this works, too.

Bye
Christof

**Comment by omersiar** [comment]
Thanks for reporting, it's time to re-enable weekly builds on Travis.
