### ISSUE TITLE
buzzer, button, localization

### ISSUE THREAD

**Issue by teriall** [omersiar/esp-rfid#36]
Hello! First of all thank you for the great project! I tried to use it as a door lock and I have a couple of questions: Is it possible to add a buzzer to make a sound when access allowed or denied and a button to unlock the door from inside for example and from settings page maybe? Is it possible to realize it for donation? :) From my side I can do localization in Polish and Russian language.

**Comment by omersiar** [comment]
Hello,

I'm very busy to make changes as you described. There are already a few things to fix and implement.

**Comment by omersiar** [comment]
Actually, there is a test button on settings page which can be used to activate the relay.
