### ISSUE TITLE
ESP File Type

### ISSUE THREAD

**Issue by dj-curls** [omersiar/esp-rfid#365]
Could someone shed some light on the .esp file type used in the src folder?

Tried googling, and it's turned up nothing useful. It looks like C++ in there. 

Why are the files defined like this, and how can I get VSCode to understand the content?

**Comment by ver2go** [comment]
Add Platform IO to VSCode if you want complete tool chain.
Otherwise change the extension to cpp for the linter then change back.
There may be a way to use the cpp linter with esp extension, but not
certain.
Or use the Arudino IDE

**Comment by omersiar** [comment]
It is because, in the beginning esp-rfid was a big monolith code. esp files introduced for better readability, but caused more harm than being useful.

**Comment by nardev** [comment]
If you set .esp to pe treated as cpp file, than you would not have any problems.

**Comment by matjack1** [comment]
As Nardev said, they are just plain cpp files that you can treat as such in your editor. It's just a custom thing of this project.
