### ISSUE TITLE
New official Release

### ISSUE THREAD

**Issue by edouardkleinhans** [omersiar/esp-rfid#378]
Hello, 

Do you know when we will have a new release for offical board ?

Latest version is 1.3.3. 

I'm waiting for keypad support.

**Comment by edouardkleinhans** [comment]
Any update ?

**Comment by edouardkleinhans** [comment]
@omersiar, any idea ?

**Comment by matjack1** [comment]
@edouardkleinhans it's coming soon!! Give or take a month and I'm pretty sure we'll be ready with some significant update :)

I'm closing this for now, but if you have any questions just let me know.
