### ISSUE TITLE
Secure mqtt and web communication

### ISSUE THREAD

**Issue by lerra** [omersiar/esp-rfid#380]
Hi,

I know its a bit tricky and limited with getting the following feature but I would love to see secure mqtt communication with client certificate instead of communication over clear text including password. Same would go for web management

**Comment by matjack1** [comment]
Hey @lerra yes, I know, I completely agree with you, but unfortunately I think this is not really feasible with an ESP8266 :(

I think you should run this on a secure wi-fi network with only a very limited access as the communication to and from the ESP are going to be unencrypted.

But please prove me wrong, I would be really happy if it was possible to encrypt web and mqtt traffic!
