### ISSUE TITLE
Cannot edit hardware settings

### ISSUE THREAD

**Issue by stmark707** [omersiar/esp-rfid#384]
Description of the hardware you are using: ESP8266 NodeMCU CP2102 ESP-12E
The version of the software that you are using: v1.0.2
exact steps to reproduce the issue: just logging into the website cannot change from weigand to RC522 device
![image](https://user-images.githubusercontent.com/66815083/84933662-16f02100-b08b-11ea-9a46-f5c95c6d18b4.png)

**Comment by stmark707** [comment]
Picture of my setup:
![image](https://user-images.githubusercontent.com/66815083/84936664-75b79980-b08f-11ea-891c-cd757e765795.png)
![image](https://user-images.githubusercontent.com/66815083/84936705-85cf7900-b08f-11ea-8689-2a6bc09c3495.png)


I am getting some new rfid testers friday, it may be a hardware issue i am unsure at the moment

**Comment by stmark707** [comment]
i updated the software to 1.3.1, and I am still not able to change the device type. I will update on Friday to see if a different RFID fixes this issue because i'm not sure how the esp8266 is supposed to detect what type of RFID it is or if even does self detect. 
![image](https://user-images.githubusercontent.com/66815083/84951560-75c29400-b0a5-11ea-8ad9-632fbc8b8e8e.png)

**Comment by omersiar** [comment]
Since you do not have the official hardware, you should flash generic.bin to your development board.

**Comment by stmark707** [comment]
Okay I will give it a try, let you know what happens

**Comment by stmark707** [comment]
that worked! thank you so much.
