### ISSUE TITLE
When will 1.3.x go form test to stable?

### ISSUE THREAD

**Issue by lerra** [omersiar/esp-rfid#386]
Hi, any plan when 1.3.x will go from test to stable? 

One funny thing is that my came with 1.0.3 and that is not available, the latest is 1.0.2.

**Comment by matjack1** [comment]
This is a bit old, but I have plans to release a new stable version soon. I'm working on some wifi improvements, then some websocket reliability improvements and then we should be ready to wrap some new documentation up and release!

Let's say a month more or less? 🤞
