### ISSUE TITLE
How can i reset my esp rfid official board? No wifi connection - wrong settings...

### ISSUE THREAD

**Issue by bib2** [omersiar/esp-rfid#389]
Hi, i must have set wrong wifi settings to my official blue esp rfid board.

Is there a way to reset it to factory default? I can´t connect to the board - no way to open the webinterface...

**Comment by omersiar** [comment]
You may re-flash SPIFFS section in order to get rid of bad configuration. You can use flash.bat on Windows PCs and select 3rd option to fully erase the firmware and SPIFFS as well.

**Comment by bib2** [comment]
Ok and how do i have to connect the esp-rfid with my windows computer? With an usb-ftdi adapter?

**Comment by omersiar** [comment]
Yes any Serial TTL adapter should work.
