### ISSUE TITLE
What is the mqtt topic? v1.3.1

### ISSUE THREAD

**Issue by XanderXVD** [omersiar/esp-rfid#392]
Those are the new features.

Added
[firmware] Support for Door Status tracking with log and mqtt options @nardev
[firmware] adding mqtt_publish_info, generateUid functions @nardev
[firmware] MQTT functionality is greatly improved, thanks to @marelab

But I don't know what the topic is can someone help me? And the acces loggin is not working.

**Comment by ingeninge** [comment]
in 1.3.3: it is a JSON string. doorip ist the ip of the ESP-RFID:
mosquitto_pub -h mastermind -t testrfid -m '{"doorip":"192.168.2.98","cmd":"opendoor"}'

**Comment by nardev** [comment]
@ingeninge tested? should we merge it?

**Comment by ingeninge** [comment]
Yes tested it just a few minutes before with a fresh installation on the Node-MCU.
