### ISSUE TITLE
always loading web data from esp8266 ON MOBILE BROWSER

### ISSUE THREAD

**Issue by paperadio** [omersiar/esp-rfid#40]
I set it in AP mode, and works well on PC web browser Chrome, eg: load user list, load log, load settings. But the web page always LOADING on my mobiel(iPhone 6S), either safari or chrome, it looks like something goes wrong on websocket, but I didn't diagnose it yet by any tools. Is it an already-known issue?

**Comment by omersiar** [comment]
I did not aware of this, let me check if i can reproduce this issue on my phone.

**Comment by nardev** [comment]
@paperadio i haven't been able to reproduce this.. can  you check it again wit newer code?

**Comment by omersiar** [comment]
I guess this behavior will be completely changed once we switch to store web files on firmware.
