### ISSUE TITLE
Updating last stable 1.0. 4 to 1.3.3 or higher 

### ISSUE THREAD

**Issue by pol-henri** [omersiar/esp-rfid#406]
Someone can explain to me how to update esp-rfid to new firmware, actually I run on 1.0.4 and want to update to 1.3.3, so I use the upload button but esp-rfid still on 1.0.4 after reboot, there is another way to update? Thanks in advance

**Comment by ingeninge** [comment]
At least you should be able to flash it with esptools via serial link. I Don't know if you can backup your data from 1.0.4 and restore it in 1.3.3, but you better make the backups before trying. If it fails you can fall back to 1.0.4 
Also consider to make a flash erase if simple overwriting with esptool fails.

**Comment by nardev** [comment]
@ingeninge can i get your email, or at least send me one at vedran@nardev.org i would like to pass you some message.

**Comment by peteshoard** [comment]
Problem seems to occur when you don't erase the flash ahead of the fresh push. 

Tasmotizer (https://github.com/tasmota/tasmotizer) makes it nice and easy, but 'Flash.bat' in the utils works also

**Comment by ingeninge** [comment]
In Linux you can do:
`esptool.py --port /dev/ttyUSB0 erase_flash` and flash with the new version.

**Comment by pol-henri** [comment]
thanks for your help

**Comment by pol-henri** [comment]
With Tasmotizer and the 1.3.3.bin file i try to update firmware , i use a TDI232 as UART serial connection , but a can't access to Esp , is  a special thing to do ?
here picture how i connect : 
https://ibb.co/w6RpNP7
https://ibb.co/jgR1kpF

thanks if you can help me on this

**Comment by nardev** [comment]
@pol-henri standard programming procedure as for any other ESP8266:

1. Press and hold FLASH button
2. Power Up the board or if it was already powered press RESET
3. Release the FLASH button

The blue led on the ESP-12F module should not be blue at that point. The module should be ready for uploading the sketch.

**Comment by pol-henri** [comment]
thanks a lot i will try it  👍

**Comment by pol-henri** [comment]
back to trying, this time i use the right procedure , but again..can't access to the Esp , i use only the VCC , GND RX, and TX from "UART" connector , i try with easyesp too , same result, so on my new "BLUE" version i try the update via UI , and this time it work !?, so lucky i try to the older RFID "GREEN" and this time after trying ..6Times or more  via UI.. it work!? perfect ! after all is what i want , now see if it solve the loosing connection MQTT after some day , i tell you

**Comment by matjack1** [comment]
hey @pol-henri not sure if it's still interesting, but sometimes this can happen if you have the pins of the ESP connected to something while flashing. Try running the procedure again on the ESP alone, only connected to the PC via USB.

I'm closing this for now, but feel free to reopen if necessary.
