### ISSUE TITLE
How to disable authentication?

### ISSUE THREAD

**Issue by nickbardom** [omersiar/esp-rfid#412]
I am trying compile esp-rfid to make it compatible to Safari browser (IOS). I am trying to find the part of the code I need to remove to disable the authentication, so it would work on Safari. Could anyone help me with that? 
As I will be using esp-rfid as an access point and I will be the only one with the password to log the access point, I don't need the authentication.

**Comment by ingeninge** [comment]
I found https://github.com/esprfid/esp-rfid/blob/stable/src/websrc/js/esprfid.js
line 1359. Function login. You can try to always let it return a successful login.

Please come back and report/close the ticket.

**Comment by nickbardom** [comment]
Hello,
Thanks for replying. I already tried that before, but it does not work with the ESP, only with the ws emulator. Another suggestion?

**Comment by nickbardom** [comment]
Hello, any news about that?

**Comment by matjack1** [comment]
hey @nickbardom I'm going to close this in favour of https://github.com/esprfid/esp-rfid/issues/302 that has more details. Please be in touch if you are still interested!
