### ISSUE TITLE
trouble building new releases

### ISSUE THREAD

**Issue by kimamov** [omersiar/esp-rfid#421]
Hey, 
did anyone try building the new releases 1.3.1 - 1.3.7 from source?
Build the stable branch works like charm but building any other version fails with a lot of errors

![image](https://user-images.githubusercontent.com/24353308/101360546-11d39800-389e-11eb-9506-773a8d82bd5f.png)

**Comment by kantimam** [comment]
okay fixed it myself :)
Looks like the platformio file in the new releases is outdated.
It needs to be replaced with the file from the dev branch

**Comment by kimamov** [comment]
okay fixed it myself :)
Looks like the platformio file in the new releases is outdated.
It needs to be replaced with the file from the dev branch
