### ISSUE TITLE
Where to find "generic.bin"?

### ISSUE THREAD

**Issue by BobbyPann** [omersiar/esp-rfid#431]
Hey everyone,

i tried to flash the code onto a NodeMCU. When I executed the flash.bat and chose option 1 nothing happend. So i looked into the flash.bat and found it is supposed to upload "generic.bin" via esptool. 

The Problem: I can't find a generic.bin in the entire ZIP-folder. 
Any ideas what i'm missing?

Thanks in advance.

**Comment by ingeninge** [comment]
You seem to have downloaded the source code. Please use the releases. See https://github.com/esprfid/esp-rfid#software
If it is the first time for you to flash esp-rfid, then please use the latest release of version 1 : https://github.com/esprfid/esp-rfid/releases/tag/1.0.2

**Comment by BobbyPann** [comment]
Thanks a lot, it worked.
