### ISSUE TITLE
Build .bin from source code

### ISSUE THREAD

**Issue by BobbyPann** [omersiar/esp-rfid#432]
Hey all,

there are some small adjustments i'd like to edit in the source code. Can anyone tell me how to create a new generic.bin from edited source code using PlatfromIO? Or is there already answer to this question that i failed to find?

Thanks in advance.

**Comment by ingeninge** [comment]
https://github.com/esprfid/esp-rfid#software
After flashing from the precompiled releases there comes:
Building with PlatformIO
