### ISSUE TITLE
PN532 does not read the UIDs of all my NFC tags

### ISSUE THREAD

**Issue by RimanCz** [omersiar/esp-rfid#434]
Hi,
I managed to plug everything in, and when I attached the NFC sticker, everything worked fine, even the tags and cards, but after I try scan my NFC Chip, nothing happens.
My 10 NFC stickers, 2 cards and 4 keychains works but NFC implant no.

Sticker UID: 92:6B:B9:3C
Chip UID: 04:06:90:8A:A0:61:81

Is the problem that my chip has a longer UID?
Thank you for your answers and help

**Comment by matjack1** [comment]
hey @RimanCz not sure if you are still interested in this, if so, please try using the latest `dev` version and use the debug target to have more info printed on the serial port, so that I can try helping you troubleshooting, OK?

**Comment by matjack1** [comment]
I'm closing this now as many things have changed and I cannot reproduce. But if this still applies, please reopen!
