### ISSUE TITLE
espr-rfid won't boot led blink no acces

### ISSUE THREAD

**Issue by pol-henri** [omersiar/esp-rfid#436]
hi, i have a problem actually with 2 rfid , whe i power up via 12v pin , the led on chip blink blue 1per/sec but don't stay fixed , actually i have no acces, i try to flash via usb uart and the device look like no react , any tips for weaking the device , it look or broken , or blocked

**Comment by matjack1** [comment]
sorry @pol-henri for the late reply, maybe it's not interesting to you anymore, but can be useful to others. When I had a similar issue, I had to disconnect the esp from the rfid device to be able to flash it. If the rfid device is not powered appropriately it might cause issues on the esp.

I'm closing this for now, but feel free to reopen if you need to.
