### ISSUE TITLE
Just an idea regarding logging - refers to https://github.com/esprfid/esp-rfid#scalability : logging needs testing

### ISSUE THREAD

**Issue by uherting** [omersiar/esp-rfid#445]
I read about the "problem" regarding logging at https://github.com/esprfid/esp-rfid#scalability

What about sending log entries to the MQTT broker from where they are taken by a Python script and stored somewhere for long term logging? I thought about this as you have got MQTT already in the project so you might get away with not much of additional effort.

**Comment by matjack1** [comment]
Yes @uherting I agree with you, it's something we are doing at the Fablab Torino, have a look here: https://github.com/FablabTorino/door-opener/blob/master/TelegramBot/main.py#L266 for an existing example :)

I'll close this, but it will pop up when searched, thank you for sharing!
