### ISSUE TITLE
Not possible to upload version 1.3.3

### ISSUE THREAD

**Issue by Enzo1604** [omersiar/esp-rfid#450]
Hello,
I wanted to upload version 1.3.3 on an esp nodeMCU. I upload via the .bat file and all of them look correct. But when I log into UI I see the version is still 1.3.1.
Is there a solution?
Thanks a lot.

**Comment by Flo2830** [comment]
Same here 1.3.1 always

**Comment by Enzo2442** [comment]
What device did you flash.
And did you immediately flash version 1.3.3 or did you flash 1.3.1 first?

**Comment by erikkt** [comment]
You probably have 1.3.3 installed, but it states 1.3.1, because someone forgot to update this line in main.cpp:
#define VERSION "1.3.1"

**Comment by matjack1** [comment]
I think this is now superseded, I'm going to close it
