### ISSUE TITLE
mfrc522 and rdm6300 not reading

### ISSUE THREAD

**Issue by nightmarebd** [omersiar/esp-rfid#452]
hi there,
im using nodemcu and rdm6300+mfrc522, wired according to esp-rfid Access Control  1.3.1 and 1.0.2. but none of my reader reads rfid cards. cant add user. can anyone help?
![IMG_20210815_171049](https://user-images.githubusercontent.com/29237019/129476575-22d76acc-9f66-4981-94cb-2d2cbfdfa6bd.jpg)

here is the config file im using.

{
  "command": "configfile",
  "network": {
    "bssid": "28:D1:27:4C:56:39",
    "ssid": "N@H!D",
    "wmode": 0,
    "hide": 0,
    "pswd": "Password321",
    "offtime": 0,
    "dhcp": 1,
    "ip": "",
    "subnet": "",
    "gateway": "",
    "dns": "",
    "apip": "192.168.4.1",
    "apsubnet": "255.255.255.0"
  },
  "hardware": {
    "readertype": 4,
    "wgd0pin": 4,
    "wgd1pin": 5,
    "sspin": 0,
    "rfidgain": 32,
    "wifipin": 255,
    "rtype": 1,
    "ltype": 0,
    "rpin": 4,
    "rtime": 400,
    "buttonpin": 255,
    "doorstatpin": null,
    "openlockpin": null
  },
  "general": {
    "hostnm": "esp-rfid",
    "restart": 0,
    "pswd": "admin"
  },
  "mqtt": {
    "enabled": 0,
    "host": "",
    "port": 1883,
    "topic": "",
    "user": "",
    "pswd": "",
    "syncrate": 180,
    "mqttlog": 0
  },
  "ntp": {
    "server": "pool.ntp.org",
    "interval": 30,
    "timezone": 0
  }
}

**Comment by crs26** [comment]
double-check the connections, if you can't select a reader from the hardware settings there must be a problem with the wiring

**Comment by Flo2830** [comment]
same for me, i can't add user

**Comment by matjack1** [comment]
hey @nightmarebd and @Flo2830 are you using the `dev` branch? If you are still interested, please try that and use the debug mode so that on the serial port you'll see much more info and I can try helping you :) Good luck!

**Comment by matjack1** [comment]
Looks like this new issue is the same: https://github.com/esprfid/esp-rfid/issues/587

I'm closing this one as I might get more feedback from the newer issue, but if someone here is still interested, please let me know.
