### ISSUE TITLE
mqtt falling back to avty=offline after time

### ISSUE THREAD

**Issue by Jamoth** [omersiar/esp-rfid#460]
In the mqtt topic rfid-esp/rfid/avty after avty is set to 'online' i observed that it is set to offline after some time, though that isnt true. The esp was has not been rebooted in that time, and the heartbeat was constantly updating. This problem occours in the latest rolling repo. As a quick and dirty workaround I'm updating avty at every hearbeat now.
The only code line where it is set to offline is in the loadConfiguration() function at the beginning, and it is set to online only once when mqtt is connected. I'm curious why it behaves that way.

**Comment by matjack1** [comment]
hey @Jamoth sorry but I'm closing this now as a lot has changed on the Home Assistant side and I wasn't able to reproduce.

Anyway, if you are still interested and if you still care about this, please reopen!
