### ISSUE TITLE
PN532 - DO NOT use GPIO15 for SS on Wemos D1 Mini   (use GPIO16 for SS instead)

### ISSUE THREAD

**Issue by hellebauer** [omersiar/esp-rfid#467]
The recommended connections for PN532 are shown in chart below.
It says to use GPIO15 (D8) for SS.  That did not work for me.

The problem is that GPIO15 is also used for Reset on Wemos D1 Mini boards.  As a result, Power-on Reset and Reset-button no longer worked  on my Wemos, while the PN532 SS-signal was hooked up to GPIO15.

I rewired the SS to GPIO16 (D0) on my Wemos and all was well afterwards. 
_(Don't forget to set SS=GPIO16 in the esprfid user interface)._

**** WIRING BELOW WILL CAUSE ISSUES with Wemos D1 Mini and PN532:
![image](https://user-images.githubusercontent.com/34071795/144401200-a3843402-ef02-4911-ad65-61a8833f765c.png)

**Comment by matjack1** [comment]
@hellebauer should we write this somewhere in the documentation, do you think?

**Comment by BaconWithThat** [comment]
Just found this and fixed my Wemos D1 mini that wouldn't boot when connected to the PN532, thank you.

**Comment by BarrMo** [comment]
Similar with my ESP8266 dev board. Set and connected to GPIO15 just seemed to jam it up. Wifi wasn't available either. I had to connect SS on the PN532 to GPIO5 (D1) Because GPIO16 (D0) is connected to the onboard LED.

**Comment by matjack1** [comment]
I hope that the new doc here: https://github.com/esprfid/esp-rfid/pull/589 sort everything out in the documentation side
