### ISSUE TITLE
37 bit wiegand support

### ISSUE THREAD

**Issue by user9685** [omersiar/esp-rfid#469]
I have a ESP_RFID Blue unit that I was planning to use with HID Proxpoint 6005 reader. The ESP-RFID will detect handle a 26 bit card, but I am trying to specifically read a 37 bit card. The reader reads the 37 bit card, as the red LED changes to green and the reader emits a beep. I do not have any additional hardware to test the reader with, but I have three of them and they all behave the same way. 

Does the ESP-RFID support 37 bit format cards? 
_

**Comment by matjack1** [comment]
hey @scienkoptic you can try changing this line here: https://github.com/esprfid/esp-rfid/blob/dev/src/rfid.esp#L7 to read the 37bit cards. I don't have such a reader to test, so I'm not 100% sure it will work.

Moreover, try different GPIO ports as depending on the device some of them might not work, but I haven't understood why. So just try different combinations before giving up!

**Comment by user9685** [comment]
Thank you so much for your help! I'll check it out once I figure out what I am doing.

**Comment by user9685** [comment]
Hi, I made this change, but also needed to update magicnumbers.h and wiegand.h library for it work.
the changes I made were to search for and replace all instances of 34 in the three files with 37. perhaps I got lucky. 

So thank you for giving me the impetus to try.
