### ISSUE TITLE
Last commit broke the user page...

### ISSUE THREAD

**Issue by nardev** [omersiar/esp-rfid#47]
Unfortunately, last commits broke the user page. It just stops at a message:

"You can add new users by either scanning a RFID Tag or by clicking on "New User" button."

And there is no add button to be shown etc..

please check, i have Wiegand version waiting for that. It's tested, works fine.. but this is confusing :(

**Comment by hagelric** [comment]
Same issue here. "fetching" data freezes...

**Comment by omersiar** [comment]
16c6869 should fix this, did not test myself, I hope you guys may test and share the result.

**Comment by hagelric** [comment]
No. 
I found the error:
After
`  wsUri =protocol+ window.location.hostname + "/ws"; 
  websock = new WebSocket(wsUri);`

File user users.js needs: (there is no "listener"). Please check log.js too.
`  websock.addEventListener('message', socketMessageListener);
  websock.addEventListener('error', socketErrorListener);
  websock.addEventListener('close', socketCloseListener);`

**Comment by nardev** [comment]
No :( didn't help...

Here is what i get in console... https://preview.ibb.co/fckbRm/Screenshot_from_2018_01_15_13_04_44.png" alt="Screenshot_from_2018_01_15_13_04_44

**Comment by nardev** [comment]
Did you fix it @hagelric ? Push Commit ???

i can't  dig in.. if  you fixed it, could you just post it ... i want to test the wiegand reader

**Comment by omersiar** [comment]
Latest commit should fix it for now. Tested with my setup.
