### ISSUE TITLE
Build fail! 

### ISSUE THREAD

**Issue by ECWSzilard** [omersiar/esp-rfid#474]
Have a nice day everyone! I would have a problem that when I want to rebuild the project I get these error messages in PlatformIO: **warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]** or this **error: no matching function for call to 'ArduinoJson :: JsonVariant :: as <long long int> () const'**. Regarding the first error message, I read that it can be solved by replacing LittleFS, but I don't get a solution to the second one at all. Has anyone encountered this problem yet?

**Comment by windy54** [comment]
How did you fix the second error ".. matching function for call...."
