### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by paoloros97** [omersiar/esp-rfid#493]
Before starting to work on a custom version, I tried to compile the code as it is.
after hitting the `platformio run` command, at the end it cames out the following error:

![image](https://user-images.githubusercontent.com/56552809/160653636-89e91147-2d1c-478f-958d-be505e2606a9.png)

`.pio/libdeps/generic/ArduinoJson/src/ArduinoJson/Deserialization/../JsonVariant.hpp:238:3: error: no type named 'type' in 'struct ArduinoJson::Internals::EnableIf<false, long long int>'
Compiling .pio/build/generic/lib5aa/AsyncMqttClient/AsyncMqttClient.cpp.o
Compiling .pio/build/generic/lib5aa/AsyncMqttClient/AsyncMqttClient/Packets/ConnAckPacket.cpp.o
*** [.pio/build/generic/src/main.cpp.o] Error 1
========================================================= [FAILED] Took 7.12 seconds =========================================================

Environment    Status    Duration
-------------  --------  ------------
generic        FAILED    00:00:07.124
=================================================== 1 failed, 0 succeeded in 00:00:07.124 ===================================================`
How can I fix it?

**Comment by grahamsingle** [comment]
Same problem - JasonVariant.hpp:
201:  //
202:  // const JsonArray& as<const JsonArray&> const;
203:  template <typename T>
204:  typename Internals::EnableIf<
205:      Internals::IsSame<typename Internals::RemoveReference<T>::type,
206:                        const JsonArray>::value,
207:      const JsonArray &>::type                                                <=========== PROBLEM HERE
208:  as() const {                                                                
209:    return variantAsArray();
210:  }

Compiler reports: .pio\libdeps\generic\ArduinoJson\src/ArduinoJson/Deserialization/../JsonVariant.hpp:208:3: error: no type named 'type' in 'struct ArduinoJson::Internals::EnableIf<false, const ArduinoJson::JsonArray&>'

**Comment by matjack1** [comment]
hey @paoloros97 and @grahamsingle it looks like you have the wrong version of ArduinoJson installed. Can you please try cleaning the target that you are compiling and trying again?

This might happen if you were on `stable`, got the old version of ArduinoJson, then moved to `dev`. Platformio doesn't get automatically the new version and happens what you are experiencing.

Let me know if how it goes!

**Comment by paoloros97** [comment]
I tried to start it again from scratch. I downloaded again the repository `git clone https://github.com/esprfid/esp-rfid.git`
then `platformio run -t clean`
and finally `platformio run`.

This is the version of ArduinoJason installed:
![image](https://user-images.githubusercontent.com/56552809/161081241-a97c9951-642a-46b9-9a3c-6b14730c722e.png)

But I got the same error :(
![image](https://user-images.githubusercontent.com/56552809/161081492-fffacc84-6557-4e8d-85e4-9a8efd70318b.png)

I copied all the outputted text in this .txt file:
[out.txt](https://github.com/esprfid/esp-rfid/files/8390438/out.txt)

**Comment by matjack1** [comment]
@paoloros97 once you've downloaded the project, you should switch to the `dev` branche.

So, clone the project, then:

`git checkout dev`

And then try again the compilation and let me know!

**Comment by paoloros97** [comment]
Thank you @matjack1 it nicely worked!
![image](https://user-images.githubusercontent.com/56552809/161207375-d09c004b-6133-47ba-85eb-ffba5729cab8.png)
:)

**Comment by matjack1** [comment]
YES! Thank you for the feedback ;)
