### ISSUE TITLE
Hardware purchase

### ISSUE THREAD

**Issue by gorstj** [omersiar/esp-rfid#507]
Hi,

Does anyone know if there are any alternative hardware suppliers?

The Tindie page linked (the original or the 'blue' board) don't seem to ship. I have purchased but then I am refunded as it hasn't shipped after a few weeks. The seller isn't answering emails.

Any idea of suitable alternatives
(don't think I could make my own with ESp8266 board as there are two many voltage changes 3.3<-->12v for my poor skills to cope with!)

Thanks for any advice.

**Comment by henfri** [comment]
Marelab.org uses a fork of esprfis and sells boards.

**Comment by matjack1** [comment]
@nardev are you shipping new boards?

**Comment by nardev** [comment]
Yes

**Comment by matjack1** [comment]
Excellent!

So whoever is interested can buy from @nardev a custom board here: https://www.tindie.com/stores/nardev/ !

**Comment by nardev** [comment]
You can ask for customization
