### ISSUE TITLE
Source code 1.0.4?

### ISSUE THREAD

**Issue by alexandergeiler** [omersiar/esp-rfid#509]
Hi,

I have version 1.0.4 installed at my board. Where can I find the source code for that release?
![1 0 4](https://user-images.githubusercontent.com/4689177/171148111-e49c1b23-f907-4f85-aa84-8e0990b65272.png)

**Comment by GosubGosub** [comment]
Seems to be some local fork not available on github.

I updated my board to the latest dev build -- works fine.

![image](https://user-images.githubusercontent.com/62539970/174642707-10a6daf3-1856-4c11-b057-315216ab086e.png)

https://github.com/esprfid/esp-rfid/actions/runs/2455804973

Upload generic.bin from the bins.zip.
