### ISSUE TITLE
Awesome project !

### ISSUE THREAD

**Issue by thbl** [omersiar/esp-rfid#510]
This project is really awesome ! Is anyone from the team available for hiring to do a custom version ?
@omersiar @matjack1

**Comment by matjack1** [comment]
hey @thbl we can discuss a bit, but as you can see from the delay in getting back to you, I'm a bit busy now. I think I'll have more time from October, but depends on what you need. Feel free to send me an email at matteo@turnintocoders.it with more details :) Thanks!
