### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by DpunktS** [omersiar/esp-rfid#513]
Is it possible to add a timer.  For example: User1 may only arrive from 06:00 to 18:00 daily.

**Comment by matjack1** [comment]
What you can do now is this:

![immagine](https://user-images.githubusercontent.com/65402/197359254-7704bc05-4260-40f1-ad58-956e66259c98.png)

you can pick opening hours for standard users, admins will open all the time.

The interface can surely be improved, but the feature works :)

I'm closing, but if you need anything else feel free to reopen.
