### ISSUE TITLE
Missing MQTT "cmd" key in message causes sytsem crash

### ISSUE THREAD

**Issue by windy54** [omersiar/esp-rfid#522]
I have been investigating issues with addusers over MQTT and my system kept crashing beause I had forgotten to add the "cmd" key to the message.
Other keys like doorip are checked for and onMQTTmessage in file mqtt.esp returns if this key does not exist.

In my test build I have modifed onMQTTmessage and added a test
`if (!mqttIncomingJson.containsKey("cmd"))
	{
#ifdef DEBUG
		Serial.print("[ INFO ] No cmd key in MQTT message: ");
		Serial.println("+++++++++++++++++++++++++++++");
#endif		
		return;
	}
		
	strlcpy(incomingMessage->command, mqttIncomingJson["cmd"], sizeof(incomingMessage->command));`

**Comment by matjack1** [comment]
Hey @windy54 I've just opened a PR to fix this: https://github.com/esprfid/esp-rfid/pull/588

Thanks! :)

**Comment by matjack1** [comment]
Merged! :)
