### ISSUE TITLE
1.3.3 binary is actually 1.3.1

### ISSUE THREAD

**Issue by nicholh** [omersiar/esp-rfid#527]
Hi,

I am having trouble getting the binary for 1.3.3. I have some boards currently running 1.3.3, but when i flash some new boards with the 1.3.3 binary downalod from Github it is actully 1.3.1.

1.3.1 does not seemt to connect to my wifi (and i am not sure about MQTT). I have tried 1.3.7 and this works but drops wifi all the time.

I was hoping sombody here could let me know where to get a cpy of the 1.3.3 binary.

Cheers

**Comment by matjack1** [comment]
hey @nicholh sorry for the delay here, the v1 is outdated and we are working towards releasing a v2.

Meanwhile, you can get the last build from here: https://github.com/esprfid/esp-rfid/actions/runs/3303810816 at the bottom of the page
