### ISSUE TITLE
Confusing with branches

### ISSUE THREAD

**Issue by evazzoler** [omersiar/esp-rfid#531]
Hi,
because I see that branches readme files are not mantained (they are identical), please, insert a global block with a simple line per branch explaining what the purpose of that branch is. I hope one day they will be merged and not become real forks... ;-)
Thank you!

**Comment by matjack1** [comment]
hey @evazzoler we have only two real branches, the others are just work in progress that I need to finish. I'm very likely to come back to the project very soon and hopefully release all the new stuff as a v2. I still want to finish the work here, it's just that I don't have time at the moment, sorry.
