### ISSUE TITLE
 read  bus card

### ISSUE THREAD

**Issue by mkeyno** [omersiar/esp-rfid#55]
sorry yo open ticket for my question , however I've tried to read my bus card with typical DumpInfo.ino example , but I can only read the card UID  and result is as per following , any advice to decode or read such card is really appreciated
``
Find new Card
Card UID: 2E 62 DF CE
PICC type: MIFARE 1KB
Sector Block   0  1  2  3   4  5  6  7   8  9 10 11  12 13 14 15  AccessBits
  15     63  PCD_Authenticate() failed: Error in communication.
  14     59  PCD_Authenticate() failed: Timeout in communication.
  13     55  PCD_Authenticate() failed: Timeout in communication.
  12     51  PCD_Authenticate() failed: Timeout in communication.
  11     47  PCD_Authenticate() failed: Timeout in communication.
  10     43  PCD_Authenticate() failed: Timeout in communication.
   9     39  PCD_Authenticate() failed: Timeout in communication.
   8     35  PCD_Authenticate() failed: Timeout in communication.
   7     31  PCD_Authenticate() failed: Timeout in communication.
   6     27  PCD_Authenticate() failed: Timeout in communication.
   5     23  PCD_Authenticate() failed: Timeout in communication.
   4     19  PCD_Authenticate() failed: Timeout in communication.
   3     15  PCD_Authenticate() failed: Timeout in communication.
   2     11  PCD_Authenticate() failed: Timeout in communication.
   1      7  PCD_Authenticate() failed: Timeout in communication.
   0      3  PCD_Authenticate() failed: Timeout in communication.
 
``

**Comment by omersiar** [comment]
`PCD_Authenticate() failed` This is the obvious reason why you couldn't decode your bus card. You do not know the authentic keys to decode.
