### ISSUE TITLE
Incorrect UID read with Wiegand 32 bit device - anyone know protocol

### ISSUE THREAD

**Issue by windy54** [omersiar/esp-rfid#556]
We currently use a 522 reader and have been donated several Wiegand devices.

These output 32 bits when a card is read.

The displayed UID is totally different to the UID stored on the card.

I have investigated the code and have a fix but this is to the Wiegand.cpp library file not the esp-rfid code.

If we had not already been using a 522 reader this issue would never have arisen.

So my question is, does anyone have a reference to the Wiegand 32 bit protocol? I can't find one.

I am going to post a similar question in the github repository for the code.

**Comment by evazzoler** [comment]
Try to check if D0 and D1 are inverted.

**Comment by windy54** [comment]
They are okay, I originally had them inverted on my logic analyser. When I work through manually the errors occur when the last bit is read in.

**Comment by matjack1** [comment]
hey @windy54 do you confirm this is something to do with the Wiegand library? Am I right?

I'm going to close this for now, but if you still need help on this one let me know. Maybe can you provide a couple of examples of RFID reads from the two sensors for the same card?

**Comment by windy54** [comment]
Hi,Yes I have edited the wiegand.cpp file, I will send the edits to you.CheersSteve GaleOn 23 Jan 2023, at 20:39, Matteo Giaccone ***@***.***> wrote:﻿
hey @windy54 do you confirm this is something to do with the Wiegand library? Am I right?
I'm going to close this for now, but if you still need help on this one let me know. Maybe can you provide a couple of examples of RFID reads from the two sensors for the same card?
