### ISSUE TITLE
Wrong admin Password at all_in_one_html

### ISSUE THREAD

**Issue by SamNitro** [omersiar/esp-rfid#56]
Hey Thunderace,
I am currently testing your all_in_one_html

Flash process was excellent :)

But he say's password ist incorrect.

**Comment by thunderace** [comment]
After any SPIFFS upload the password is empty i think

**Comment by SamNitro** [comment]
empty is not allowed at input

**Comment by thunderace** [comment]
I know now, no config -> AP Mode -> default password in AP mode : "admin", elementary :)

**Comment by SamNitro** [comment]
admin is wrong :(

**Comment by thunderace** [comment]
You're right. I never use the AP mode because i'm working remotely (my ESP8266 is connected to a remote server).
The last commit fix this i think.

**Comment by SamNitro** [comment]
Perfect, login is correct thx.
will continue testing :)
