### ISSUE TITLE
Cant save reader settings in new build

### ISSUE THREAD

**Issue by stupsi099** [omersiar/esp-rfid#568]
Platformio build #100
green official board and wiegand reader HID RP10

If you try to change wlan and press save yellow line apears and it works
if you try to change reader settings and press save - nothing - no yellow line

**Comment by konradhuebner** [comment]
I tried the same today, also does not work for me. It does not show the "save" button, and also does not restore the settings in the webpage. It does however save parts of it. The Wiegand setting incl. D0/D1 were saved, but the beeper and LED were not

**Comment by hinkma** [comment]
I try setup Wiegand. Save button web page not do nothing to log. 
Second one problem is that 'LED access denied OFF' running all the time  terminal.

**Comment by hinkma** [comment]
I make Factory reset and now LED access denied OFF' running not active any more.
Every time when I click save button, ESP reboot itself.

**Comment by stupsi099** [comment]
With build #101 save works again.

**Comment by matjack1** [comment]
Thank you for the feedback. I'm going to close for now, but feel free to reopen if necessary
