### ISSUE TITLE
all in one HTML/JS/CSS files

### ISSUE THREAD

**Issue by thunderace** [omersiar/esp-rfid#57]
done

 in the "all_in_one_html" branch.
Need some work/test for backup and restore.

- [ ] test settings backup and restore
- [ ] investigate some esp8266 crashes
- [x] fix user acces type bug on new user (always displayed as disabled')
- [x] fix user 'valid until' format on user edit
- [x] fix scan detection (web part)
- [ ] fix add user replace the first line in table (sometimes)
- [x] expand the log table width to the parent

**Comment by SamNitro** [comment]
i have another issue
after flash I can not change everything in settings page
he says "please wait while fetching data..." and nothing happens

**Comment by omersiar** [comment]
I will test this.

**Comment by omersiar** [comment]
`src\web_server_static_files.h:2:36: fatal error: web_server.required.js.h: No such file or directory`

**Comment by omersiar** [comment]
After installing Java, now this: `[src\esp-rfid.ino.cpp] TypeError : unsupported operand type(s) for -: 'float' and 'NoneType'`

I did not know the Java is required.

**Comment by omersiar** [comment]
I do not know how I built it but now i can flash, but i can not access web pages through my phone.

**Comment by omersiar** [comment]
- [ ] Place a warning if there is no Java available during pio_script.py:19  `if java_installed:`

**Comment by omersiar** [comment]
Both required.js and .css files are actually coming from JQuery, Bootstrap, FooTables, it will be nice to have them separately and combine them during compile time, so they can be updated whenever they receive an update.

**Comment by SamNitro** [comment]
can you edit anything on the settings page?

**Comment by SamNitro** [comment]
<img width="280" alt="bildschirmfoto 2018-01-18 um 20 47 53" src="https://user-images.githubusercontent.com/30635514/35118046-e6ce04ca-fc90-11e7-9452-1a8822acbea8.png">

**Comment by thunderace** [comment]
@omersiar i think you're not on the right branch : java is used in the "embedded-html" branch, not this one.
And if java is not installed there is a fallback to inline minify so you need an internet connection.

@SamNitro if you cannot edit the settings page it's because the config file is not loaded (for whatever reason).

**Comment by SamNitro** [comment]
I don't now, it will not work.

**Comment by thunderace** [comment]
@SamNitro My bad, i fix something for the AP mode. I haven't see the bug before because i never use this mode (i always upload my config file).
Try the last commit. It will work now...

**Comment by SamNitro** [comment]
Perfect :)

Now I'm just waiting for MQTT and Schedule User Access then I'm happy ;)

**Comment by thunderace** [comment]
Hum... another bug fix in the last commit... sorry

**Comment by SamNitro** [comment]
if you add a user it's not show in the page tab "Access Type". After reload the page it's correct

**Comment by thunderace** [comment]
Do you use the last commit?. you know, i make many bug fixes so look frequently the commits.

**Comment by SamNitro** [comment]
Yes it‘s the last commit. I check regularly if there is something new ;)

**Comment by thunderace** [comment]
Sorry to ask this but do you upload the SPIFFS at each new commit?

**Comment by thunderace** [comment]
I just upload the spiffs and firmware from the last commit and i see no error on user add...
Strange

**Comment by SamNitro** [comment]
Yes i Upload Both from last commit. 

Add a new User and Label it Activ and than change the the view only Activ User

**Comment by omersiar** [comment]
<link rel="icon" href="/favicon.ico">
    <link href="/required.css" rel="stylesheet">
    <script src="/required.js" type="text/javascript"></script>
    <script src="/auth/settings.js" type="text/javascript"></script>
    <script src="/auth/users.js" type="text/javascript"></script>
    <script src="/auth/log.js" type="text/javascript"></script>
    <script src="/auth/esprfid.js" type="text/javascript"></script>

Can your Browsers load all these resource with one shot?

**Comment by SamNitro** [comment]
I dont know.. How can i test it?

**Comment by thunderace** [comment]
> Add a new User and Label it Activ and then change the view only Activ User

Ok, i see. working on this... This is just the filter

Edit : don't understand... Perhaps a Footable bug?

**Comment by SamNitro** [comment]
hey thunderace do you have time to add mqtt support?

**Comment by thunderace** [comment]
@SamNitro : no i can do nothing for now : my house is flooded and i'am in it (France, La Seine, floods).

**Comment by SamNitro** [comment]
oh I'm sorry. then I hope that is not too much broken.

**Comment by omersiar** [comment]
@thunderace sorry to hear, i hope everthing get better
