### ISSUE TITLE
Unlocking from Homeassistant by MQTT

### ISSUE THREAD

**Issue by timknowlden** [omersiar/esp-rfid#573]
Hi, what is the mqtt message that needs to be sent to esprfid to activate the relay (unlock the door) I cannot find MQTT payloads listed anywhere?

**Comment by matjack1** [comment]
Hey @timknowlden have a look at the documentation here: https://github.com/esprfid/esp-rfid/blob/dev/README-MQTT.md#open-door

It's on the `dev` branch, but I recommend you to use that. I hope to be able to merge into stable soon!
