### ISSUE TITLE
Keypad login

### ISSUE THREAD

**Issue by timknowlden** [omersiar/esp-rfid#575]
I have no set up my keypad weigand reader, am I mistaken but is only the rfid tag supported method of access or can the number pad be used also?

**Comment by timknowlden** [comment]
Numbers are picked up in the  add user page, but only the 1st number. So if i want to add PIN 1234 as soon as i press '1' it opens add user.

**Comment by timknowlden** [comment]
Forgive me, upload of newer firmware must have failed, I have re-uploaded 1.3.7 (which is listed as 1.3.1) and the keypad now waits for # to be pressed which allows me to enter longer pin numbers.

**Comment by timknowlden** [comment]
I don't know where to post this but how can I find, download and install the latest dev branch?

**Comment by matjack1** [comment]
Hey @timknowlden you can get here the last dev build: https://github.com/esprfid/esp-rfid/suites/10269592798/artifacts/504177320

In general here: https://github.com/esprfid/esp-rfid/actions you can find all the builds for all the branches and commits, OK?

Let me know if you still have problems. Cheers

**Comment by timknowlden** [comment]
Thanks, I thought I read somewhere the was home assistant auto discovery and ability to include the bell button from keypad with latest dev build.

**Comment by matjack1** [comment]
yes @timknowlden the auto-discovery on Home Assistant is there and should be working :)

For the doorbell, it's part of the HA integration, but I'm not sure if you are talking about something particular on your keypad.

You can drive the doorbell with a pin, I hope this helps.

**Comment by timknowlden** [comment]
Sadly I have no option to enable a doorbell pin in the settings, unless I am mistaken and looking in the wrong place?

<img width="938" alt="Screenshot 2023-01-22 at 20 08 46" src="https://user-images.githubusercontent.com/73787006/213937893-7d3786f4-033c-4dd5-8ba9-e03958b8b175.png">

**Comment by matjack1** [comment]
hey @timknowlden looks like you are not on the `dev` branch, look how it should look like on `dev`:

![Schermata 2023-01-22 alle 21 24 09](https://user-images.githubusercontent.com/65402/213938604-472da65e-206c-4384-88ed-c038400dfae5.jpg)

**Comment by timknowlden** [comment]
Ah that's good to know, perhaps it is not uploading then when I try here to upload latest file:
<img width="584" alt="Screenshot 2023-01-22 at 20 28 01" src="https://user-images.githubusercontent.com/73787006/213938752-ede2f701-5076-4578-a27f-816c75de952d.png">

**Comment by matjack1** [comment]
strange @timknowlden it should work from there too. I'll try myself soon

**Comment by matjack1** [comment]
It takes a while to update, if you can try again in debug mode with the serial monitor attached, and if you can share the logs it would help to see what's going on in your setup.

Let me know if you have more news. Maybe you can try again and just wait a bit to make sure that the process has finished.

**Comment by timknowlden** [comment]
Yes, I'll try to update again by UI. 

I've also picked up a 12v relay to try and get the doorbell sensor working as my keypad has 2 doorbell wires but needs a 12v supply, the esp only gives 3 or 5v.
