### ISSUE TITLE
MQTT restart

### ISSUE THREAD

**Issue by timknowlden** [omersiar/esp-rfid#584]
Hi, 
Sometimes my device becomes unresponsive via mqtt command. I haven't yet worked out if its due to the device or the server.

I have to restart the esp device to get it to respond again. Is there a way to restart the connection without restarting device and automatically too? 

Running the latest dev build.

Also when I restart my device it sends a message by mqtt to say the door has been opened by the push button. Is there a way to disable this message being sent, or change the message to say device has restarted. 
![Screenshot_20230310_162547_Brave](https://user-images.githubusercontent.com/73787006/224370668-775aaf4f-a348-44bd-aa11-fd3d7aa36d28.jpg)
![Screenshot_20230310_162611_Brave](https://user-images.githubusercontent.com/73787006/224370705-7d9d39d6-c41b-452b-a4ec-aa663a10ecdf.jpg)
![Screenshot_20230310_162547_Brave](https://user-images.githubusercontent.com/73787006/224370709-27daadf5-a474-445b-b6b9-90a89499f77c.jpg)

**Comment by matjack1** [comment]
hello @timknowlden are you only sending MQTT commands and then it stops responding or are you also using the Web UI?

If MQTT only, which messages are you sending?

**Comment by timknowlden** [comment]
It's only mqtt commands that it is not working with.

The Web ui is still functional and that is how I'm restarting the device

**Comment by matjack1** [comment]
Can you share a log of calls that you are sending/receiving from the esp-rfid, so that I can try reproducing? Or some steps that you take that reproduce the problem. I have a very stable system with MQTT (mostly sending from esp-rfid)

**Comment by timknowlden** [comment]
I am using home assistant to issue commands via mosquito broker, the log will be flooded with messages to and from other devices. It can last for days on end before becoming unresponsive. 

If the message on restart was not that the door was operated then I could set the device to restart daily?

**Comment by matjack1** [comment]
Yes @timknowlden that's what I would do! You can setup the autorestart from here:

![immagine](https://user-images.githubusercontent.com/65402/224489505-ed79bac9-9981-4a29-9035-9a574eed14e6.png)

You can also set a custom time, if 24h are too much.

I'm going to close this for now, but reopen if this is not good enough. Unfortunately there's only so much we can do from esp-rfid to mitigate these type of issues.

**Comment by timknowlden** [comment]
I had a power cut at home today. The esprfid device started sooner than the server so no connection to mqtt broker was made. I therefore was unable to open by home assistant.

The device then needed manually restarting from the UI. 

The only message I received was a new connection in mqtt log.

This gives a message to home assistant to say the device was operated by button which it was not. It simply just connected to the broker.
![Screenshot_20230313_151849_Home Assistant](https://user-images.githubusercontent.com/73787006/224746232-a06ba014-2b60-4a50-a879-e07bb35d4ae6.jpg)
