### ISSUE TITLE
Problem reading tags with RDM6300

### ISSUE THREAD

**Issue by teodino93** [omersiar/esp-rfid#587]
Hi, 
I'm using the dev branch and flashed the project on a D1 Mini, the RDM6300 TX is connected to the RX of the board and VCC and GND is shared between the two boards.
I can read the tags with an example sketch, but with esp-rfid nothing comes on the serial.
I tried to print the serial output from the genericRead function in rfid.esp and it's always 0, if I change the baud rate of the serial port to 9600 something is coming out but still isn't reading them as tags.

If you need more information feel free to ask.
Thank you

**Comment by matjack1** [comment]
hey @teodino93 can you share the sketch that works? Maybe we can start from there :)

Unfortunately I don't have a RDM6300 to test, so I need to rely on you helping me out, OK?

If there's anyone else that can help it would be really helpful, by the way.

**Comment by matjack1** [comment]
@teodino93 have a look at this: https://github.com/esprfid/esp-rfid/issues/558 might give you a hint?

**Comment by matjack1** [comment]
Actually, have you seen the doc:

![immagine](https://user-images.githubusercontent.com/65402/228359888-f3a3214d-0761-447c-b31b-1326afcaf7b6.png)

It looks like you should connect RDM6300 TX to GPIO-03, right?

Let me know!

**Comment by teodino93** [comment]
Hi!
I have used the example sketch on this library: [https://github.com/arduino12/rdm6300](https://github.com/arduino12/rdm6300)
In my D1 mini the GPIO-3 is the RX pin, shared with the HardwareSerial.
The pin is correct because it reads a series of 0 when i approach the tag, but the RDM6300 needs a serial of 9600 baud, if I change it in the main code it reads the ID but the code after the but RFIDr.Available() is still false.
Can we think about using a different serial (or implementing that library) for reading the RDM6300?

**Comment by matjack1** [comment]
hey @teodino93 I saw the example, and it's using a different library and different approach. Probably would be better to switch to that library, or at least change approach in the serial usage, as they are doing in the example.

More information on the two serials here: https://arduino-esp8266.readthedocs.io/en/3.1.2/reference.html#serial if someone can help it would be nice! :) I'll give it a try at some point, but any help is appreciated.

**Comment by teodino93** [comment]
Perfect! I think I can test something on saturday, I'll be in touch if i achieve something!

**Comment by teodino93** [comment]
I've created the PR #591  to fix the problem, no need for the library i linked, we can use a SoftwareSerial just for the RDM6300

**Comment by timknowlden** [comment]
> I've created the PR #591 to fix the problem, no need for the library i linked, we can use a SoftwareSerial just for the RDM6300

How can i test? Im also using UART to send a number over serial. However my use case is from an rf receiver. I cant see any data being received on the esprfid when connected to GPIO4 or RX

**Comment by matjack1** [comment]
Hey @timknowlden are you using the code in the PR #591? 

I've had successfully tested that PR. It needed a bit more polish, but it was working. Are you sending data at the right baud rate? You need to send data at 9600.

If you want to help on the PR I'm happy to guide you, it needs to add a bit of configuration and a bit of cleaning :)

**Comment by matjack1** [comment]
Fixed here: https://github.com/esprfid/esp-rfid/pull/655
