### ISSUE TITLE
In case of interrupt, log can be damaged.

### ISSUE THREAD

**Issue by nardev** [omersiar/esp-rfid#60]
I have one client which was not able to retrieve log. When i downloaded the latestlof json file, i noticed that the log file was actually interrupted so the format was damaged.

If possible, please others test this case.. once the card is swiped and reader is interrupted, does anything wrong happen.

I hope i'm wrong.

**Comment by goermezer** [comment]
@nardev : I had the same issue. Could solve it by removing the log file. Hole thread here: https://github.com/omersiar/esp-rfid/issues/39

**Comment by nardev** [comment]
@goermezer @omersiar i'll try to test another way of writing the log..

Some clients i have, need that so it's not good if the log disappears..

Also, most of wiegand readers have keypad so i'll write and extensio that each user can have pin too. As an optional way to open the doors.

**Comment by akeilox** [comment]
@nardev for wiegand readers with keypad, does it work if you enter card's decimal id manually?
Do you have to press a certain key after like # or other key after entering id?

just to chip in to the discussion, while trying out the wiegand reader with esp-rfid, if the 12V connection broken or re-established to the wiegand reader, the log file will capture single digit like 0 and next line 7.
Not something you'll normally encounter but I did recall the 'log file corrupted' discussions when i first saw it.

**Comment by omersiar** [comment]
Logging is horribly inefficient, and also has a bug on file checking. @rneurink's approach was better and i forgot to fix my code.

At that time we were discussing different approaches for logging but it did not conclude, so if you make suggestions, we can start to work on it. Just do not bother with the current code.

**Comment by nardev** [comment]
@akeilox wiegand readers  usually have two buttons for exit or enter.. so at the end you can clear the number you entered or submit it to check if it exists among the users. However, that option is not yetin repo.

@omersiar i need some time to test to see if it works fine. The idea i have.

i want to check pure file logging with events in a form


    - Log file
    --------------------------------------------------------------
        (Parse with JS if possible for UI???)
      - Simple log:

        TIMESTAMP:TYPE:UID

        Example:

        1517457827:RFID:123:CARD
        1517457827:PIN:134
        1517457829:DOOR:0|1
        1517457830:BELL (write once in 30 seconds)
        1517457831:PIR

        Where:
        RFID: 0
        PIN: 1
        DOOR: 2
        BELL: 3
        PIR: 4


We could do better for user interface.. That json is very handy but if we can make same thing without json  log much more efficient,  why not.

@omersiar since we have one reset in 24hours maybe we  could add log size check before that reset.. just to keep 1-2 months log or certain  size..

**Comment by nardev** [comment]
@akeilox  there is my board which can handle 12V for ESP and pass 12V to a reader.
Check it: https://www.tindie.com/products/nardev/esp-rfid-board-for-wiegand-readers-at-5v-to-28v/

If you want i can send you few without ESP12 module.. i have some that have a mistake for a reset button but everything else works.

**Comment by akeilox** [comment]
@nardev thanks for the offer! i dropped you a message at tindie

**Comment by omersiar** [comment]
See v6.0

**Comment by omersiar** [comment]
See v0.6
