### ISSUE TITLE
Improve rendering of uptime in web UI

### ISSUE THREAD

**Issue by stupsi099** [omersiar/esp-rfid#607]
if you look in status field you can see only a rising number (no date/time)
not shure if its a bug or a feature.

![grafik](https://github.com/esprfid/esp-rfid/assets/40528102/db2277b2-054e-4df6-9359-2670bb7a8bc8)

br
rupert

**Comment by matjack1** [comment]
Hey @stupsi099 the uptime is in seconds now. I agree that it would be nicer if it was parsed and shown in days/hours/seconds.

If anyone wants to try improving that let me know, I can help giving you directions on how to implement this.

**Comment by pvtex** [comment]
this is no problem just change the file _wsRepsonse.esp_
in the function 
```
void ICACHE_FLASH_ATTR sendStatus(AsyncWebSocketClient *client)
```

change this line:
```
root["uptime"] = uptimeSeconds;
```
tp:
```
int h = uptimeSeconds / 3600;
int rem = uptimeSeconds % 3600;
int m = rem / 60;
int s = rem % 60;
char uptimebuffer[9];
sprintf(uptimebuffer, "%02d:%02d:%02d", h, m, s);
root["uptime"] = uptimebuffer;
```

**Comment by omersiar** [comment]
Rather than making the transformation on limited esp hardware, it would be better to handle it on Client side (browser).

**Comment by matjack1** [comment]
True, but I think that's also fine as pvtex did. It's now on dev, closing this!
