### ISSUE TITLE
Tag UID isn't read while using MFRC522 and v2.0.0.rc0

### ISSUE THREAD

**Issue by MaximeSharp** [omersiar/esp-rfid#617]
Hi,
While testing the new release, I've noticed that scanning a tag does trigger the device but the tag UID isn't read, so it's impossible to register a new card or trigger the relay pin.

![screencapture-192-168-1-29-2024-02-10-02_48_18](https://github.com/esprfid/esp-rfid/assets/13646650/5760933e-0676-4b3d-9ba6-fb4019ee9395)

MQTT does also report that a unknown tag has been scanned and the UID is empty too.

![2024-02-10_04-27-16](https://github.com/esprfid/esp-rfid/assets/13646650/aa8c62ec-d069-472a-b003-bf95a922b11a)

I've confirmed that my setup is working using the version 1.3.7, and it's working fine.

![screencapture-192-168-4-1-2024-02-10-03_11_24](https://github.com/esprfid/esp-rfid/assets/13646650/82e643d4-c01e-4976-8461-0ee357617584)

**Comment by ewc-beep** [comment]
Hi
you can find the solution here -> https://github.com/esprfid/esp-rfid/issues/610

**Comment by MaximeSharp** [comment]
Hi,

Thanks, seems like I didn't search enough or used the wrong keywords to find this solution.
I'm out of stock of MFRC522, but once I receive my order I will compile the dev branch to test it again.
