### ISSUE TITLE
How to get latest generic.bin for Dev branch

### ISSUE THREAD

**Issue by neel8440924** [omersiar/esp-rfid#628]
Sorry for posting this here, but I am new to GitHub , can someone please build generic.bin for latest Dev branch, I tried building myself with platform up but was unsuccessful

**Comment by stupsi099** [comment]
https://github.com/esprfid/esp-rfid/actions/runs/8621879570

br Rupert

**Comment by neel8440924** [comment]
Thankyou so much I don't know how did I miss that
