### ISSUE TITLE
Latestspiffs for wiegand reader of last arduino release

### ISSUE THREAD

**Issue by JuculianD** [omersiar/esp-rfid#65]
Hello, I have a problem with the spiff files for the last arduino version.
The option for the wiegand reader is missing in the settings.
![image](https://user-images.githubusercontent.com/29288242/36725325-dfd2c0ca-1bad-11e8-9cf1-49b68f0548b8.png)

I am trying to use that wiegand reader. It has an ST microcontroller on it.
Does it work?

Thanks for the development.

BTW, when will the new bootstrap web interface be ready?

Julian.

**Comment by omersiar** [comment]
Hello @JuculianD,

The wiegand setting is not missing, it was not there at all in that release. So you need to wait for new release but i can not going to release it any time soon.

If your wiegand module with ST MCU is compatible with the protocol itself it should work as a reader.

**Comment by JuculianD** [comment]
Thank you very much. I will wait for it. When approximately will it be ready?
I am building a codelock system for a school.
 Thank you for that development and license.

**Comment by nardev** [comment]
@JuculianD ther is an old release which supports wiegand readers, have it working in some places. Also check this board https://www.tindie.com/products/nardev/esp-rfid-board-for-wiegand-readers-at-5v-to-12v/

I made it specially for wiegand readers. 

Get this commit for wiegand readers: https://github.com/omersiar/esp-rfid/tree/f098df91b01ec2b9158f621790c12e24ea34932f

**Comment by omersiar** [comment]
@JuculianD Hello,

I know you are waiting for it, you can build stable branch, it should have Wiegand reader support (i'm not sure tbh).

**Comment by JuculianD** [comment]
@nardev
Thanks for the tindie link. I got it working. The boards are looking fine.
Are they preflashed with the firmware? How does the table data
synchronization work.

2018-02-28 15:53 GMT+00:00 Julian Dahl <vesteckt@gmail.com>:

**Comment by JuculianD** [comment]
Thanks Oemer for the help! Unfortunately, your tindie link doesn't work.

2018-02-28 15:36 GMT+00:00 Ömer Şiar Baysal <notifications@github.com>:

**Comment by nardev** [comment]
@JuculianD check again :D sorry https://www.tindie.com/products/nardev/esp-rfid-board-for-wiegand-readers-at-5v-to-12v/

**Comment by nardev** [comment]
This is 50% promo code for the board:  F468260E

 https://www.tindie.com/products/nardev/esp-rfid-board-for-wiegand-readers-at-5v-to-12v/

**Comment by JuculianD** [comment]
I need help... I have the 7941E v3.0 Reader but I cant read out anything. The reader has an UART and Wiegand option. I dont have any more information. Does somebody have an Idea?

**Comment by JuculianD** [comment]
![img_20180302_094714](https://user-images.githubusercontent.com/29288242/36893113-ca160dca-1dfe-11e8-934d-d02e52162ba6.jpg)
![img_20180302_094702](https://user-images.githubusercontent.com/29288242/36893115-ca38f0e2-1dfe-11e8-9dfc-ff35e06deeb4.jpg)

**Comment by nardev** [comment]
You must use both wires for wiegand. That is the idea about the protocol. So hook D0 and D1, both to ESP. And determine which GPIO's are corresponding to that wemos, set it like that and there you go.

**Comment by JuculianD** [comment]
I have both connected!

On 2 Mar 2018 15:07, "nardev" <notifications@github.com> wrote:

You must use both wires for wiegand. That is the idea about the protocol.
So hook D0 and D1, both to ESP. And determine which GPIO's are
corresponding to that wemos, set it like that and there you go.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/omersiar/esp-rfid/issues/65#issuecomment-369945820>,
or mute
the thread

**Comment by nardev** [comment]
Ou  see now.. at first i saw only white one... well, did you determine which GPIOs are corresponding to wemos pins?

**Comment by JuculianD** [comment]
Yes, I put them in the settings page. I tried different pins as well, and I also tried a 3A 5V power supply now.

What is wrong? Is the reader damaged?

**Comment by nardev** [comment]
@JuculianD so you use D7 and D8 which is GPIO 13 and GPIO 15.

And you used the commit that i suggested?

https://github.com/omersiar/esp-rfid/tree/f098df91b01ec2b9158f621790c12e24ea34932f

And you uploaded the spiffs files?

Am i right?

**Comment by JuculianD** [comment]
I am using Pin D6 for D0 and 
D7 for D1.

**Comment by JuculianD** [comment]
And no, I am not using your commit, because I does say invalid password for the login.

**Comment by JuculianD** [comment]
And failed to open config file. I dont know why, but my wemos d1 mini is struggling with some firmwares?

**Comment by nardev** [comment]
It's ok if you don't have config file, it will be recreated.

I don't know about new commits but the one i gave you, works 100%. If you have time, try that one.

**Comment by JuculianD** [comment]
The new commit works fine, except of wiegand. Your commit doesn't work, I can't login.

**Comment by nardev** [comment]
admin is the password
