### ISSUE TITLE
esp-rfid reboots when logs are accessed.

### ISSUE THREAD

**Issue by FOSSBOSS** [omersiar/esp-rfid#650]
Not sure yet if it is just me, or if it is everyone using this project.
When I try to access the logs, I get :
"Please wait while fetching data."
no amount of waiting helps, it never returns the logs. 

an additional issue i have is that from the "logs" section, access, or event, 
the link to the status section doesn't work. Ill have a look at the code there in a minute.

esp-rfid Access Control  1.0.2

**Comment by matjack1** [comment]
Hey @FOSSBOSS can you try building the `dev` branch? It should be much better.

I'll have a go hopefully soon in releasing a new v2 release candidate as we should be close to release now!

**Comment by matjack1** [comment]
Hey @FOSSBOSS I've just release a new release candidate for V2 here: https://github.com/esprfid/esp-rfid/releases/tag/2.0.0.rc1

I hope it will work better, let me know if you can! :)

**Comment by FOSSBOSS** [comment]
I will check that out! Thanks!
