### ISSUE TITLE
esprfid_js.h: saventp(): Invalid use of parseInt() where there is a possible requirement for a float

### ISSUE THREAD

**Issue by microfoundry** [omersiar/esp-rfid#652]
Greetings - the DropDownTimezone list contains several option values with fractional remainders.

Currently, the esprfid_js.h: saventp(): calls:

`config.ntp.timezone = parseInt(document.getElementById("DropDownTimezone").value);`

The proper call would be:

`config.ntp.timezone = parseFloat(document.getElementById("DropDownTimezone").value);`

Best regards - Terry

**Comment by matjack1** [comment]
hey @microfoundry thank you very much for this report.

It's changed quite a bit in the `dev` branch, which is the one that you should use if you want to try this project! It's going to be the v2 of this project, I hope at some point soon :)
