### ISSUE TITLE
Wifi client

### ISSUE THREAD

**Issue by SamNitro** [omersiar/esp-rfid#73]
Hi, I can not connect to my Wifi, after save and reboot he is still in AP mode. 

version 0.5.3

**Comment by romanzava** [comment]
Hello,
the problem is that you have to connect PIN 16 with logical 1, so that means 3v3 or 5V, I am using the ESP12 and i have 5V connected there.

The condition for the formating is created to compare pin 16 with LOW and if the condition is true then call the reset  of the device.

**Comment by SamNitro** [comment]
Thank you it works :)

**Comment by SamNitro** [comment]
hey, same problem with the new version 0.6.1 he will stay in ap mode.
(Nodemcu and Wemos D1 mini)

is there another solution?

**Comment by omersiar** [comment]
Are you sure D0 is high enough? Because i did not reproduce this issue.

**Comment by SamNitro** [comment]
No idea where the problem was, now it works again.
