### ISSUE TITLE
New user with incorrect validity

### ISSUE THREAD

**Issue by romanzava** [omersiar/esp-rfid#74]
Hi,

adding the user via GUI always store only the default validity to 1970-01-01.

**Comment by romanzava** [comment]
So I identified the problem,

I see, that the portal is sending null object of validity on esp
{"command":"userfile","uid":"sasdfasdf","user":"sdafasdfasdfasdf","acctype":"1","validuntil":null}

Web is showing correct value for the validuntil in espfind.js but the incorrect value for the vuepoch

esprfid.js
line 703 i added some logs after
            var vuepoch = (new Date(validuntil).getTime() / 1000) + (timezone * 60 * 60);
            console.log(validuntil);
            datatosend.validuntil = vuepoch;
            console.log("epohc" + vuepoch);

output on web console
```
2038-01-01
epohcNaN
```

Question to @omersiar , why we are working with the timezone there ? 
When i removed (timezone * 60 * 60) now the web store it properly.

**Comment by omersiar** [comment]
At some poimt i was testing NTP libraries, each library behave different about timezone. Now i think it's now good continue with curret one, so these issues with NTP will be fixed.
