### ISSUE TITLE
Scan of wifi returns more columns of the same wifi

### ISSUE THREAD

**Issue by romanzava** [omersiar/esp-rfid#75]
Hi,

when I do a scan of wifi i see there are more times the same wifi networks.
![obrazok](https://user-images.githubusercontent.com/29689146/37176863-edc14f90-231d-11e8-9a29-74a32d18effb.png)

**Comment by SamNitro** [comment]
my scan is correct.
![1](https://user-images.githubusercontent.com/30635514/37177599-3de33cde-2320-11e8-9d2c-b3b554ca2f0d.png)

**Comment by romanzava** [comment]
are some networks on N standard ? Because I think that it is messing it up a little.

**Comment by SamNitro** [comment]
my PC network is N standard:

![1](https://user-images.githubusercontent.com/30635514/37177919-3222f7da-2321-11e8-8eb6-94ad5232e4d5.png)

**Comment by omersiar** [comment]
This is because of the recent limit. Loop does not take account number of the networks found, this is why you always see 5 networks, if there are 5 or more networks, this is not a problem.

@romanzava thank you.

**Comment by omersiar** [comment]
Fixed with d873042
