### ISSUE TITLE
Status page doesnt show the updated firmware version

### ISSUE THREAD

**Issue by akeilox** [omersiar/esp-rfid#80]
I was on v.6
saw the .6.1 update, wanted to give it a try via the web ui.
downloaded the firmware, named "firmware (2).bin" and applied.

Upon completion there is no feedback, is it supposed to redirect or do something?
manually refreshed and status page shows "esp-rfid Access Control  v0.6" not the .6.1 like in the demo url https://bitadvise.com/esp-rfid/

Is there a way to manually restart the esp via the web ui?

**Comment by omersiar** [comment]
Feedback after completion would be nice. I will add it. Also you are right about version, i will fix it in next release.

There is no manual restart. I will add it on Backup & Restore page.

Thank you for feedback. Have a nice day.
