### ISSUE TITLE
Can't change config

### ISSUE THREAD

**Issue by fjfricke** [omersiar/esp-rfid#84]
Hello together

Thanks for developing that wonderful software. Unfortunately I cannot change any settings as the following is sent over the serial connection:

> [ WARN ] Failed to open config file
> [ INFO ] ESP-RFID is running in Fallback AP Mode
> [ INFO ] Configuring access point... Ready

What is the problem there and how can I solve it?

**Comment by omersiar** [comment]
The problem is that you need to connect gpio 16 to 3.3v

**Comment by fjfricke** [comment]
Thank you!

**Comment by alegiovannelli** [comment]
Today i flashed the new version but i can't config some details in 'hardware settings' like imege attached.
Some combo box are locked.
Ihave also connected gpio 16 to 3.3v with no success.

Thank you in advance.
![download](https://user-images.githubusercontent.com/29068703/44116781-bcebd400-a011-11e8-9c30-66f509ec21a4.png)

**Comment by omersiar** [comment]
You flashed the v2board firmware binary, unless you have the official esp-rfid board you should have flashed generic.bin file.

**Comment by alegiovannelli** [comment]
I did not notice the error during the flash, but by repeating it and paying attention I can now configure the hardware.
Thank you, wonderful project!
