### ISSUE TITLE
Globilization

### ISSUE THREAD

**Issue by JuculianD** [omersiar/esp-rfid#86]
I would like to translate into German. I would be happy if there is something like a language/translation file.

**Comment by omersiar** [comment]
I am now considering best approach for globalization.

**Comment by wejder669** [comment]
Hello All,
Could translate into Polish.
How many values are there to translate?

**Comment by omersiar** [comment]
I'm closing this because there is no easy way to translate the whole project, unless we refactor the WebUI.  It will take time and I prematurely set it to 0.8 milestone and realized that it will take longer later.  So do not expect globalization at this time.

**Comment by PierfrancescoElia** [comment]
I'm available to translate into Italian.
Feel free to contact when ready.

Thank you.

**Comment by roysbike** [comment]
I can translate into Russian.
