### ISSUE TITLE
Settings > MQTT Settings (shows disabled when enabled)

### ISSUE THREAD

**Issue by pidiet** [omersiar/esp-rfid#92]
Hello @omersiar 

just found out while testing mqtt that the settings page is always showing "**disabled**" even when the mqtt is enabled (freshly restarted after applying settings) and publishing messages to my local mqtt server.

![image](https://user-images.githubusercontent.com/28258387/38032288-8e18a2ca-329d-11e8-9a90-4a991daa1e4e.png)

**Comment by omersiar** [comment]
Done.
