### ISSUE TITLE
Time does not sync with ntp

### ISSUE THREAD

**Issue by pidiet** [omersiar/esp-rfid#93]
Hello!

I have the problem that my time does not get synced with ntp. Not the stock settings nor my local ntp server are working. Devices always starts back in the year 1970....

The local sync with the browser works as expected but needs manual trigger.

![image](https://user-images.githubusercontent.com/28258387/38032747-ab17e934-329e-11e8-9497-d9f665be664f.png)

**Comment by omersiar** [comment]
It maybe related by DNS name resolution.

**Comment by pidiet** [comment]
Really! It worked right away when giving the IP address of my local ntp server.

I think (my) esp-rfid is **not able to resolve host names only for ntp** (my mqtt is configured with host name and is working fine)

**Comment by omersiar** [comment]
Actually lwip has async DNS resolution, I can refactor the NTP code, it will be rock solid with fallback server, check for dead NTP server,  etc I simply do not have time. I should mention these in known issues.
