### ISSUE TITLE
button to open from inside

### ISSUE THREAD

**Issue by teriall** [omersiar/esp-rfid#95]
Is it possible to use one more pin for a button which will trigger the relay to open a door from inside?

**Comment by omersiar** [comment]
You can connect button to relay circuit.

**Comment by teriall** [comment]
ok:)

**Comment by teriall** [comment]
I add the push button to trigger relay from the inside. Maybe possible to add in to the code? 
![photo_2018-06-28_12-06-07](https://user-images.githubusercontent.com/4177449/42012878-0b3c71a6-7acd-11e8-9789-8c3c93550c2a.jpg)

**Comment by omersiar** [comment]
I think esp-rfid should not endorse additional hardware other than simply basic RFID reader support and a door lock trigger mechanism.  LCDs, Buzzers, Speakers, LEDs, Buttons does not fit for all, some are comfortable with Buzzer, some are implementing LCD.

We should keep it this way.

**Comment by PierfrancescoElia** [comment]
Hi @teriall, I'm interested in adding a button.
Cloud you please share with the community your changes? 

I would really appreciate that! 
Thank you, have a nice day! :)

**Comment by teriall** [comment]
I'll try to do it somehow.
update:
Here is it. Compiled firmware in bin folder, or you can compile it by yourself as well.
https://github.com/teriall/esp-rfid
