### ISSUE TITLE
esp-rfid Does not boot anymore when upgraded to 0.7

### ISSUE THREAD

**Issue by omersiar** [omersiar/esp-rfid#99]
Please download latest version firmware.bin [here](https://github.com/omersiar/esp-rfid/releases/latest) https://github.com/omersiar/esp-rfid/releases/latest

**You Need To Clear Browser's Cache or Open ESP-RFID Web UI on Browser's Incognito Mode**

* Make sure you have a user's backup ( do not back up settings )
* Before upgrading make a factory reset.
* After factory reset connect to esp-rfid's Access Point.
* Do not setup any configuration
* Do firmware upgrade
* Configure your newly upgraded device
* Save and Reboot
* Restore Users back.

Or Windows PC users can use flash tool which is available on /bin folder

* Make sure you have a user's backup ( do not back up settings )
* use erase.bat
* then use flash.bat

**Comment by pidiet** [comment]
True.

Just tried an update from web ui from 0.7.0 to 0.7.2 (without any prerequisites) and my device was blowing away...

**Comment by omersiar** [comment]
Not modified header will be dropped, since the firmware actively changing, we do not need it for now.  It can be enabled again when we hit the v1.
